### PR TITLE
PHP updates

### PR DESCRIPTION
**Pull request by stayallive**
Improves and adds PHP snippets and docs.

### CODE REVIEW

**Comment by stayallive** [comment]
@PeloWriter why hasn't this been merged? Are there still approvals pending or work needed?

**Comment by PeloWriter** [comment]
@stayallive - There are conflicts that need to be addressed before it can be merged. We generally anticipate that the originator of the PR resolves these conflicts.

**Comment by stayallive** [comment]
@PeloWriter oh snap. I'm sorry... I'm sure they were not there when I submitted 😓 

Probably some changes since I submitted and the approval. Will fix those up!

**Comment by PeloWriter** [comment]
:) I should have pinged you earlier, when I saw that this PR was aging. Thanks for making these updates!

**Comment by stayallive** [comment]
@PeloWriter is there still something to do here for me before this can be merged?

**Comment by PeloWriter** [comment]
No, I will go ahead and merge. Thanks for the nudge.

**Pull request merged**
