### PR TITLE
doc(relay): PII guide is for static mode

### PR DESCRIPTION
**Pull request by jjbayer**
## Pre-merge checklist

*If you work at Sentry, you're able to merge your own PR without review, but please don't unless there's a good reason.*

- [x] Checked Vercel preview for correctness, including links
- [x] PR was reviewed and approved by any necessary SMEs
- [x] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## Description of changes

In order to clarify that editing PII settings in project configs is for Relay Static Mode only:

1. Move the guide under "Relay Modes,
2. add "Static Mode" to the title.

Fixes https://github.com/getsentry/sentry/issues/67755.

### CODE REVIEW

**Review by olksdr — APPROVED** [review]

**Review by Dav1dde — APPROVED** [review]

**Review by vivianyentran — APPROVED** [review]

**Review by cstavitsky — APPROVED** [review]
👍 

Would it also make sense, either here or as a separate PR, to add PII scrubbing examples for managed mode? This may help for those who are not that familiar with the different modes.

**Comment by vivianyentran** [comment]
+1 on adding PII scrubbing examples! that would be super useful!

**Comment by jjbayer** [comment]
> Would it also make sense, either here or as a separate PR, to add PII scrubbing examples for managed mode?

@cstavitsky added a paragraph about managed mode now. In managed mode, rules are configured through the UI and then propagated to the Relay instances running on the user's premises.

**Review by iker-barriocanal — APPROVED** [review]

**Review by cstavitsky — APPROVED** [review]
👍 thanks for adding the managed mode piece!

**Pull request merged**
