### PR TITLE
feat: Add sampling documentation

### PR DESCRIPTION
**Pull request by dcramer**

### CODE REVIEW

**Comment by dcramer** [comment]
As we inch towards the APM launch this kind of conversation (around sampling) is going to be increasingly important and visible inside of the product. This sets us up for a basis to expand and also hits an important keyword in search: "sampling"

**Comment by dcramer** [comment]
Also just now realizing that a lot of this was under Quotas - id like to move away from Quotas/Rate Limits and focus on client side sampling. It's less costly for us and less prone to abuse.

**Comment by dcramer** [comment]
(so we could consider combining the quotas doc into this, and maybe minimize the rate limits component?)

**Comment by MimiDumpling** [comment]
> (so we could consider combining the quotas doc into this, and maybe minimize the rate limits component?)

I think this sounds reasonable. I'll sync up with Katie to see if she has an extra insights.

**Comment by MimiDumpling** [comment]
> So has this been superseded by #1062 or are they both still live? (Left some comments there.)

Hi @lobsterkatie, yeah let's keep the conversation on #1062 for now -- since that's where most of the comments are. In the end, we'll go with @dcramer's suggestion and make it one page with a heavy emphasis on Sampling. Will definitely appreciate your help with that. :D

**Pull request closed without merging**
