### PR TITLE
clarify that maxBreadcrumbs can be customized

### PR DESCRIPTION
**Pull request by imatwawana**
Fixes https://github.com/getsentry/sentry-docs/issues/4496

### CODE REVIEW

**Comment by imatwawana** [comment]
@liamjones - I haven't linked this your issue to the PR, since this might not be the only PR associated with it, but wanted you to be able to review the wording here and see if it's clearer to you.

**Comment by liamjones** [comment]
@imatwawana Yep, that's helpful! I wasn't aware of the 1MB limit before this...

**Comment by imatwawana** [comment]
Converting this to draft until we've figured out exactly what changes need to be made in source code documentation.

**Comment by marandaneto** [comment]
> Converting this to draft until we've figured out exactly what changes need to be made in source code documentation.

This can be merged after https://github.com/getsentry/sentry-javascript/issues/4693 gets done and released.

**Comment by imatwawana** [comment]
> [getsentry/sentry-javascript#4693](https://github.com/getsentry/sentry-javascript/issues/4693) was resolved so we can merge this when we cut the next JS SDK release

Thanks, @Lms24! Can you drop a note on this PR when that happens?

**Comment by AbhiPrasad** [comment]
Released with https://github.com/getsentry/sentry-javascript/releases/tag/7.14.2!

**Pull request merged**
