### PR TITLE
docs(laravel): More straight-forward performance onboarding

### PR DESCRIPTION
**Pull request by benvinegar**
Instead of having a separate block for Performance, include it in the environment variable guide for DSN and add a note about reducing volume or even opting out.

I also suggest here strictly using the environment variable configuration method, since we already do that for DSN. If there's a reason we should show the alternate setup (which, fwiw, I didn't even know where to put), please let me know @HazAT.

After:

image

### CODE REVIEW

**Review by PeloWriter — APPROVED** [review]
Nice. We'll adopt this language.

**Review by dcramer — APPROVED** [review]

**Comment by benvinegar** [comment]
I just want to get @HazAT's take before merging.

**Comment by dcramer** [comment]
also #2388

**Review by HazAT — APPROVED** [review]

**Comment by benvinegar** [comment]
Going to revisit this because the Laravel wizard (launches when you run `php artisan sentry:publish`) literally asks you if you want to set up Performance Monitoring (and defaults to yes). Choosing "yes" has the effect of updating the .env file automatically.

```bash
 Enable Performance Monitoring? (yes/no) [yes]:
[Sentry] Added `SENTRY_TRACES_SAMPLE_RATE=1` to your .env file.
```

Seems redundant to add a block about editing the .env file manually.

**Comment by HazAT** [comment]
Closing this then, to clean up stale PRs

**Pull request closed without merging**
