### PR TITLE
ref(codeBlock): Reskin code context menus

### PR DESCRIPTION
**Pull request by EvanPurkhiser**
Added some nice animations and cleaned up colors a bit

https://user-images.githubusercontent.com/1421724/108353023-7ebbb600-719c-11eb-991d-2f1f655b1077.mov

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
Damn, this marginally breaks copy and paste.. annoying af

**Comment by PeloWriter** [comment]
Really like the option to select the DSN here. Thank you.

**Comment by EvanPurkhiser** [comment]
> Really like the option to select the DSN here. Thank you.

We actually had this before, but I just gave it a fresh coat of paint + some little animations

**Review by scefali — APPROVED** [review]
LGTM

**Pull request merged**
