### PR TITLE
Add test for usePlatform() when specifying an explicit platform

### PR DESCRIPTION
**Pull request by torarnv**
The bug was fixed by ca52c4269f5, this just adds a test.

### CODE REVIEW

**Comment by torarnv** [comment]
cc @cameronmcefee

**Comment by torarnv** [comment]
cc @bruno-garcia

**Comment by torarnv** [comment]
This is a leftover after 9c5b84142ac818551027 in https://github.com/getsentry/sentry-docs/pull/2842

**Comment by torarnv** [comment]
@Swatinem

**Review by bruno-garcia — APPROVED** [review]
Oh I assigned reviews before reviewing the code!
LGTM, thanks @torarnv

**Comment by cameronmcefee** [comment]
Huh, this was already fixed in #3249. ¯\_(ツ)_/¯. Thanks for the tests @torarnv!

**Comment by torarnv** [comment]
> Huh, this was already fixed in #3249. ¯\_(ツ)_/¯. Thanks for the tests @torarnv!

Hehe, yeah, I fixed the same bug in 9c5b841 in #2842, but it got stale and didn't merge 😊 Doing some cleanups now 😊

**Pull request merged**
