### PR TITLE
update slack alert image

### PR DESCRIPTION
**Pull request by vivianyentran**
update screenshot of slack alert

### CODE REVIEW

**Comment by ceorourke** [comment]
Looks good but this is just in EA for now, might be a bit until GA.

**Comment by vivianyentran** [comment]
Sounds good, will wait til GA then

**Comment by vivianyentran** [comment]
@ceorourke @Dhrumil-Sentry Are the slack alerts still in EA? Any update on timeline for when we should publish this doc update?

**Comment by ceorourke** [comment]
> @ceorourke @Dhrumil-Sentry Are the slack alerts still in EA? Any update on timeline for when we should publish this doc update?

The goal is to GA next Monday :) We'll let you know when this is ok to merge!

**Comment by vivianyentran** [comment]
@ceorourke any update?

**Comment by ceorourke** [comment]
> @ceorourke any update?

😢 sorry it's taking longer than expected, the team is dealing with some unexpected bugs. If you want to join #proj-slack-improvements you can follow along, otherwise I'll let you know when it's been released.

**Pull request merged**
