### PR TITLE
Highlight replay snippets

### LINKED ISSUE #9340: Apply Highlighting to Replay Code Snippets in Docs
Update any docs to use this new feature: <https://vanguard.getsentry.net/p/cltd2gded0000s60q671bjal5>
- Highlighting of lines
- New way to show diffs

## Tasklist of Where We Can Update Docs for Highlighting

- [x] Highlight Replay sample rates and new Replay integration block on [this code snippet](https://docs.sentry.io/platforms/javascript/session-replay/#set-up)
- [x] Highlight `Sentry.replayCanvasIntegration()` on [this code snippet](https://docs.sentry.io/platforms/javascript/session-replay/#canvas-recording)
- [x] Highlight ` networkRequestHeaders: ["Cache-Control"],
  networkResponseHeaders: ["Referrer-Policy"],` on this [code snippet](https://docs.sentry.io/platforms/javascript/session-replay/configuration/#network-details)
  
 Note that these changes should be reflected for all applicable platforms.

[Slack Message for Context](https://sentry.slack.com/archives/C04RDSY3ML1/p1709587154375279?thread_ts=1709587154.375279&cid=C04RDSY3ML1)

### PR DESCRIPTION
**Pull request by a-hariti**
## Pre-merge checklist

*If you work at Sentry, you're able to merge your own PR without review, but please don't unless there's a good reason.*

- [ ] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## Description of changes

Closes #9340

### CODE REVIEW

**Comment by jas-kas** [comment]
Screenshot 2024-03-15 at 8 06 24 AM

Looks like both replay sample rates are not being highlighted. We should highlight this line too `replaysOnErrorSampleRate: 1.0,`. Otherwise, LGTM :)

**Comment by billyvg** [comment]
Also they're highlighted in red, which generally implies it should be removed. Is there a way to highlight them as green?

**Comment by a-hariti** [comment]
That's Sentry brand pink not red, green is usually for diff +. You can see the difference on this PR #9456  [preview](https://sentry-docs-git-contributing-docs.sentry.dev/contributing/pages/components/#code-blocks)

But in the end that's just CSS, we can change it to something else if there's a consensus.

**Comment by billyvg** [comment]
> That's Sentry brand pink not red, green is usually for diff +. You can see the difference on this PR #9456 [preview](https://sentry-docs-git-contributing-docs.sentry.dev/contributing/pages/components/#code-blocks) @billyvg
> 
> But in the end that's just CSS, we can change it to something else if there's a consensus.

Ahh I see... could we use the diff syntax and use `+`?

**Comment by a-hariti** [comment]
The diff syntax comes with the annoyance of copying the `+` and `-` symbols along with code,
so I'd hesitate to use unless it's necessary (like a migration example)

We can change the color (one line CSS change), we just need to agree on which one.
@billyvg

**Comment by michellewzhang** [comment]
went through all the platforms + changes on the vercel preview + verified we're highlighting all the correct lines -- all look good to me!

**Review by michellewzhang — APPROVED** [review]
could change the color per @billyvg's request but otherwise 🚢🚢

**Comment by billyvg** [comment]
Let's leave as-is :shipit:

**Review by jas-kas — APPROVED** [review]

**Pull request merged**
