### PR TITLE
Added documentation for customizing fragment lifecycle breadcrumbs

### PR DESCRIPTION
**Pull request by ILikeYourHat**
Documentation change related to https://github.com/getsentry/sentry-java/pull/2299

- [x] Merge after sentry-java is released with the new change

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Review by romtsn — APPROVED** [review]

**Comment by romtsn** [comment]
@imatwawana could you perhaps authorize the Vercel deployment? For some reason when I click "approve" it does nothing

**Comment by ILikeYourHat** [comment]
This feature is now released in sentry-java 6.7.0. Can we merge this PR now? :)

**Comment by romtsn** [comment]
> This feature is now released in sentry-java 6.7.0. Can we merge this PR now? :)

Sure thing, I've been looking through the open PRs for docs after the release, but missed this one. Sorry!

**Comment by ILikeYourHat** [comment]
No problem, thank you :)

**Pull request merged**
