### PR TITLE
feat(apple): Carthage visionOS support

### PR DESCRIPTION
**Pull request by philipphofmann**
## Pre-merge checklist

*If you work at Sentry, you're able to merge your own PR without review, but please don't unless there's a good reason.*

- [x] Checked Vercel preview for correctness, including links
- [x] PR was reviewed and approved by any necessary SMEs
- [x] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

Related Cocoa PR https://github.com/getsentry/sentry-cocoa/pull/3565.

### CODE REVIEW

**Review by shanamatthews — APPROVED** [review]
👍

**Comment by lizokm** [comment]
Hey there, @philipphofmann! Since we've moved docs over to Next.js, if this PR is still relevant, could you rewrite it please? (Nothing has changed in the docs contribution process other than that we have to add images/PDFs to the"public" folder for them to be visible.) Thanks and sorry for the extra work!

**Comment by philipphofmann** [comment]
That's not a problem. Where are the Next.js docs?

**Comment by lizokm** [comment]
Thank you, @philipphofmann! Next.js has taken over Gatsby and lives in the same repo where Gatsby used to live. So nothing has really changed and you can still use your code editor of choice :) It's just that none of the unstaged changes will be visible in the new Next.js docs, which is why you have to rewrite them.

**Comment by philipphofmann** [comment]
OK got it. Here we go https://github.com/getsentry/sentry-docs/pull/9047.

**Pull request closed without merging**
