### PR TITLE
feat(sourcemaps): Mention volume sharing across web & workers

### PR DESCRIPTION
**Pull request by daicoden**
Add something to the docs about how to get source maps to work with docker deployed environment.

### CODE REVIEW

**Comment by BYK** [comment]
Why do we need this, the on-premise repo ensures this already?

**Comment by daicoden** [comment]
Apologies, I guess I'm running an older version of sentry. 9.0 I started everything manually. This was the fix for me, but it might be worth putting in the README something generic that for sourcemaps to work the worker and web need to share a volume - however that may be.

**Comment by daicoden** [comment]
FYI @BYK

from: https://hub.docker.com/_/sentry/

```
SENTRY_FILESTORE_DIR
Directory where uploaded files will be stored. This defaults to /var/lib/sentry/files and is a VOLUME for persistent data.
```

**Comment by BYK** [comment]
@daicoden 

>Apologies, I guess I'm running an older version of sentry. 9.0 I started everything 
manually.

No need to apologize, in fact _I apologize_ as you took the extra mile to submit a fix for an issue you encountered and reading my initial response, it is not very encouraging.

Thanks a lot for submitting this 🙂 

>from: hub.docker.com/_/sentry

This image is locked on 9.1.2 unfortunately and we are working with Docker folks to update it. We encourage everyone to use [the official on-premise repo](https://github.com/getsentry/onpremise) for installation in all channels but I guess we need to update this page too :)

**Pull request merged**
