### PR TITLE
docs(security-policy-reporting): note expect-ct header deprecation

### PR DESCRIPTION
**Pull request by dargmuesli**
## DESCRIBE YOUR PR
This header is deprecated by now.

## IS YOUR CHANGE URGENT?     

Help us prioritize incoming PRs by letting us know when the change needs to go live. 
- [ ] Urgent deadline (GA date, etc.): 
- [ ] Other deadline: 
- [x] None: Not urgent, can wait up to 1 week+

## PRE-MERGE CHECKLIST

*Make sure you've checked the following before merging your changes:*

- [ ] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## LEGAL BOILERPLATE

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by vivianyentran** [comment]
@oioki Do you know if there's any other updates we need to make for the expect-ct deprecation? Can we just remove the entire section?

**Comment by dargmuesli** [comment]
@vivianyentran should we proceed with this PR without a reply from @oioki?

**Comment by vivianyentran** [comment]
@mdtro Can you take a look at this PR? Do you know if there's any other updates we need to make for the expect-ct deprecation? Can we just remove the entire section?

**Comment by dargmuesli** [comment]
:(
seems like commenting wasn't enough

**Pull request closed without merging**
