### PR TITLE
fix(github): Fix GitHub SSO Auth URL

### PR DESCRIPTION
**Pull request by BYK**
Follow up to #1487, addressing https://git.io/JvZMx

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
There may be a reason it needs to be like this. It depends on if github shares the same app for integrations and SSO (which It might, I need to verify)

**Comment by BYK** [comment]
>It depends on if github shares the same app for integrations and SSO (which It might, I need to verify)

It doesn't but it can and I already verified this myself. This was also mentioned in the original issue: https://github.com/getsentry/onpremise/issues/373#issue-558531728

**Comment by EvanPurkhiser** [comment]
Did we actually change this URL? These are both valid URLs in Sentry.

**Comment by BYK** [comment]
I only changed the user auth URL which makes sense here. The integration still uses the setup URL, well, as the setup URL.

**Pull request merged**
