### PR TITLE
Added example

### PR DESCRIPTION
**Pull request by dkrito**
Added how to unset user at logout in the scopes page.

### CODE REVIEW

**Comment by dkrito** [comment]
@MimiDumpling I removed the test file. Would you check if it is all good?

**Comment by MimiDumpling** [comment]
I'm pretty sure this is correct, but tagging @kamilogorek and @billyvg to double check the code snippet for accuracy and formatting. 🌻

**Comment by MimiDumpling** [comment]
@dkrito you'll need to update your snapshot. I think that's why the tests are failing.

**Comment by kamilogorek** [comment]
It's `setUser(null)` – https://github.com/getsentry/sentry-javascript/blob/ef7b3b2dd02af063138f7453f8c7d92e033365b8/packages/types/src/hub.ts#L115-L120

**Comment by kamilogorek** [comment]
The syntax for it is `setUser(null)`

https://github.com/getsentry/sentry-javascript/blob/master/packages/types/src/hub.ts#L115-L120

**Comment by kamilogorek** [comment]
The syntax for it is `setUser(null)`

[](https://github.com/getsentry/sentry-javascript/blob/master/packages/types/src/hub.ts#L115-L120)

**Comment by MimiDumpling** [comment]
> The syntax for it is `setUser(null)`
> 
> https://github.com/getsentry/sentry-javascript/blob/ef7b3b2dd02af063138f7453f8c7d92e033365b8/packages/types/src/hub.ts#L115-L120
> 
> Also, this is a generic page template, and the JS syntax will be displayed even for different languages. It should be either moved to `_documentation/enriching-error-data/configure-scope/javascript.md` or included as a separate snippet.

@dkrito opened a different PR for this: https://github.com/getsentry/sentry-docs/pull/1416

**Comment by kamilogorek** [comment]
Superseded by https://github.com/getsentry/sentry-docs/pull/1416

**Pull request closed without merging**
