### PR TITLE
Improve pricing faq

### PR DESCRIPTION
**Pull request by dcramer**

### CODE REVIEW

**Comment by dcramer** [comment]
I've removed various bits which were hardcoded (and repetitive). Its my opinion that going forward this document should focus on complexities, and not repeat everything shown on the marketing pages. If people want to know the price, they can view it in app or on the marketing page.

**Comment by dcramer** [comment]
I'm going to wait to merge this til Wednesday just FYI

**Comment by MeredithAnya** [comment]
💰

**Comment by dcramer** [comment]
shipping now to avoid shipping at 8am

**Pull request merged**
