### PR TITLE
meta(gha): Deploy action issue-status-helper.yml

### PR DESCRIPTION
**Pull request by BYK**
I are a bot, here to deploy [issue-status-helper.yml](https://github.com/getsentry/.github/blob/57bd472f2ba4a4fe2b6273d2efef592786e7e664/.github/workflows/issue-status-helper.yml). 🤖

### CODE REVIEW

**Comment by chadwhitacre** [comment]
Is this related to the failure at https://github.com/getsentry/sentry-docs/runs/2642260294?check_suite_focus=true?

**Comment by BYK** [comment]
Nope, that failure is related to https://github.com/cli/cli/issues/3346

**Comment by chadwhitacre** [comment]
Oh, right. So this is just catching up?

**Comment by BYK** [comment]
Yup, not sure how this was missed last time :(

**Pull request merged**
