### PR TITLE
fix: reintroduce distributed tracing section

### PR DESCRIPTION
**Pull request by supervacuus**
It seems like this `PlatformSection` has been accidentally deleted in this PR: https://github.com/getsentry/sentry-docs/commit/a6ef44ce1b2c36391346ad120775a55748129b30 back in June. I guess it was accidental because the referenced `PlatformContent` [is still there](https://github.com/getsentry/sentry-docs/tree/master/src/platform-includes/performance/distributed-tracing) (except for `dotnet` which was removed as part of this PR: https://github.com/getsentry/sentry-docs/pull/8024). I can only speak for the Native SDK, but we still need the docs for this (users cannot find how to continue traces to/form the Native SDK). Maybe the maintainers of the other SDKs can chime in (@kahest, @Swatinem, ...).

### CODE REVIEW

**Review by Swatinem — APPROVED** [review]

**Comment by shanamatthews** [comment]
@stephanie-anderson - we may have accidentally gotten rid of useful information about how to set up distributed tracing for dart, flutter, rust, and C/C++ when we moved twop docs to the Usage section. 

For languages like c/c++ where users still need to enable performance monitoring for tracing to work, does it make sense to re-add this content to the new Distributed Tracing section inside Usage? Or should this work automatically with performance turned on for languages like c/c++ now and users should no longer need to manually propagate headers like [these instructions explain](https://sentry-docs-git-fork-supervacuus-fix-reintroduce-distrib-23bbcb.sentry.dev/platforms/native/performance/instrumentation/custom-instrumentation/#distributed-tracing).

As a side note, for the Java docs, I'm not sure if the [original distributed tracing content](https://sentry-docs-git-fork-supervacuus-fix-reintroduce-distrib-23bbcb.sentry.dev/platforms/java/performance/instrumentation/custom-instrumentation/#distributed-tracing) is meaningfully different than [the new](https://sentry-docs-git-fork-supervacuus-fix-reintroduce-distrib-23bbcb.sentry.dev/platforms/java/usage/distributed-tracing/custom-instrumentation/).

**Comment by supervacuus** [comment]
Just wanted to ping shortly, since this has been open for over a month. Thx!

**Comment by kahest** [comment]
@supervacuus thank you for creating this PR. As @shanamatthews pointed out above, the docs structure changed a bit. I will open a PR to re-add the lost pieces for the mentioned platforms in the appropriate places in the new structure and link it here.

**Comment by supervacuus** [comment]
> As @shanamatthews pointed out above, the docs structure changed a bit.

To be clear, I also found the existing structure extremely complicated, and I don't understand to this day why the (distributed) tracing and instrumentation functionality isn't part of _Usage_. 

But the structure or overloaded nomenclature ("performance" vs. "(distributed) tracing" vs. "instrumentation", where each chapter then immediately references any of the other terms within the first paragraph) to me was secondary to the missing content. While not all "performance" users might need to continue a trace in or from the Native SDK, it did make sense to have them in the vicinity of the other functions.

**Comment by kahest** [comment]
Gonna close this in favor of https://github.com/getsentry/sentry-docs/pull/8842 now

**Pull request closed without merging**
