### PR TITLE
update Strapi link

### PR DESCRIPTION
**Pull request by imatwawana**
Update dead link to new Strapi plugin for v4+

### CODE REVIEW

**Comment by imatwawana** [comment]
@remidej - Does this update look good to you?

**Comment by imatwawana** [comment]
@remidej - nudge

**Review by remidej — COMMENTED** [review]
Yes thanks it's a good fix for this broken link. I just think that we can remove the v4+ text but as you want

**Comment by imatwawana** [comment]
> Yes thanks it's a good fix for this broken link. I just think that we can remove the v4+ text but as you want

Thank you!!

**Pull request merged**
