### PR TITLE
Correct typo

### PR DESCRIPTION
**Pull request by carehart**

### CODE REVIEW

**Comment by carehart** [comment]
Is this failure, "Enforce License Compliance", related to something I've failed to do? Or just a temporary problem of some sort in the pr workflow process, that someone on the Sentry team would handle?

**Comment by marandaneto** [comment]
> Is this failure, "Enforce License Compliance", related to something I've failed to do? Or just a temporary problem of some sort in the pr workflow process, that someone on the Sentry team would handle?

Not sure, it's new, @imatwawana or @chadwhitacre  might know about it.

**Review by philipphofmann — APPROVED** [review]
Thanks a lot 👍

**Comment by imatwawana** [comment]
> > Is this failure, "Enforce License Compliance", related to something I've failed to do? Or just a temporary problem of some sort in the pr workflow process, that someone on the Sentry team would handle?
> 
> Not sure, it's new, @imatwawana or @chadwhitacre might know about it.

@chadwhitacre, can you take a look please?

**Comment by dashed** [comment]
@imatwawana feel free to ignore for this pull request. You may merge this pull request.

**Comment by chadwhitacre** [comment]
(Sorry for the trouble re: license check, I've disabled for now until I can debug.)

**Pull request merged**
