### PR TITLE
Fix sentry-cli installation directions

### PR DESCRIPTION
**Pull request by mattrobenolt**
This will future proof us by handling redirects, and updates to the canonical apex, rather than www.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
For what it's worth i intentionally did not make it use redirects because that makes people even more uncomfortable running these one-liners. But I'm fine doing the change. That said: this now forces a redirect which just makes the install a tiny bit slower :)

**Comment by mattrobenolt** [comment]
Why does this force a redirect?

I just want to make sure we don't unintentionally break this in the future.

**Comment by mitsuhiko** [comment]
@mattrobenolt because getsentry.com/get-cli is a redirect to www.getsentry.com/get-cli

**Comment by mattrobenolt** [comment]
No it's not.

**Comment by mitsuhiko** [comment]
WTF? Since when?

**Comment by mitsuhiko** [comment]
In that case, go ahead.

**Pull request merged**
