### PR TITLE
[Develop Docs] Clean up "SDK Development" Sidebar

### PR DESCRIPTION
**Pull request by antonpirker**
## DESCRIBE YOUR PR
Organize the content in the "SDK Development" section of the develop docs better. 

Preview: https://develop-docs-git-antonpirker-developsdk-sidebar.sentry.dev/getting-started/

Todos:
- [x] Fix links in all the pages moved
- [X] Add redirects from old to new location of pages

Screenshot 2024-10-14 at 10 22 22

## IS YOUR CHANGE URGENT?  

Help us prioritize incoming PRs by letting us know when the change needs to go live.
- [ ] Urgent deadline (GA date, etc.): 
- [ ] Other deadline: 
- [X] None: Not urgent, can wait up to 1 week+

## SLA

- Teamwork makes the dream work, so please add a reviewer to your PRs.
- Please give the docs team up to 1 week to review your PR unless you've added an urgent due date to it.
Thanks in advance for your help!

## PRE-MERGE CHECKLIST

*Make sure you've checked the following before merging your changes:*

- [X] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs (subject matter experts)
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## LEGAL BOILERPLATE

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

## EXTRA RESOURCES

- [Sentry Docs contributor guide](https://docs.sentry.io/contributing/)

### CODE REVIEW

**Comment by bruno-garcia** [comment]
looking just at the screenshot on the description: looks like a great improvement. Thanks Anton!

**Comment by stephanie-anderson** [comment]
Looks amazing Anton, thank you!

**Comment by sentrivana** [comment]
Looking great, thanks for cleaning this up!

**Comment by philipphofmann** [comment]
This makes sense to me. Thanks @antonpirker 👍

**Comment by antonpirker** [comment]
Because almost no text was changed (only pages where moved around to have better structure of the information) I will merge this without docs team reviewing it.

**Review by sentrivana — APPROVED** [review]

**Pull request merged**
