### PR TITLE
adding new styles and making it somewhat more accessible

### PR DESCRIPTION
**Pull request by stevenplewis**
### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Review by imatwawana — COMMENTED** [review]
I haven't tested the screen reading yet, but a few things:

1. The styling is overriding a change we made before where if a word had a hyperlink in it in already, then we didn't want to the word to have the glossary underline or the tooltip:


2. When the tooltip is displayed, it covers up regular text, but not other terms that have tooltips:


3. The sidebar causes the tooltip not to display:


4. If the tooltip bumps into a note, the tooltip disappears:


Though this doesn't seem to be consistent between browsers and (on Firefox the note disappears in one case, but a weird note that's not rendering properly on Safari and Firefox causes the tooltip to disappear).

5. On Safari, the underlines don't show up.

All of these examples are on this page: https://sentry-docs-git-docs-term-tooltip-design-update.sentry.dev/product/accounts/quotas/

6. The pink is intense. Can we make it either less red or less bright without losing too much contrast?

**Comment by imatwawana** [comment]
I'm only testing VoiceOver on Safari since that's the only browser it's really meant to work well with. It's pretty good, but it doesn't tell you there's a definition or tooltip happening so it just sort of launches into it. 

Btw I haven't tested on IE. I can circle back with that tomorrow.

**Comment by stevenplewis** [comment]
@imatwawana All the things in your first comment should be addressed now, and I added an aria-label to the tooltip so it will announce itself more clearly to address your second comment. I think adding the label requires more button presses for the reader to advance to the tooltip, then the content of the tooltip, then out of the tooltip, then back to the rest of the text, but it's probably clearer this way. Good call.

**Review by imatwawana — APPROVED** [review]
All the visual stuff looks good now and I like the new underline and tooltip colour a lot more. Also, the screen reading sounds good too. Looks great!

**Review by untitaker — CHANGES_REQUESTED** [review]
nice!

**Review by untitaker — APPROVED** [review]

**Comment by imatwawana** [comment]
Because this change adds in screen reading of tooltips, let's not merge this until we've reduced the instances of a glossary pop-up to once per page. cc @untitaker

**Pull request merged**
