### PR TITLE
Ensure that the `<Route>` component is imported in example code

### PR DESCRIPTION
**Pull request by jasikpark**
## Pre-merge checklist

*If you work at Sentry, you're able to merge your own PR without review, but please don't unless there's a good reason.*

- [ ] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## Description of changes

This PR updates the example code for the react-router-dom@v6 integration

(an aside - is there a recommended path for using https://github.com/remix-run/react-router/blob/main/packages/react-router-dom-v5-compat/README.md to transition between the two sentry setups?)

## Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

## Extra resources

- [Sentry Docs contributor guide](https://docs.sentry.io/contributing/)

### CODE REVIEW

**Review by AbhiPrasad — APPROVED** [review]
Thanks for your contribution!

**Comment by AbhiPrasad** [comment]
> is there a recommended path for using https://github.com/remix-run/react-router/blob/main/packages/react-router-dom-v5-compat/README.md to transition between the two sentry setups

We don't have anything atm, but PRs are welcome to our docs if you feel something needs to be highlighted!

**Comment by jasikpark** [comment]
Yeah, I kinda just did it in one large feature branch, so I'm just now integrating at the end. Do you know whether the SentryRoutes approach is necessary for *every* Routes component in a RRv6 app? Or just the top-level one?

in RRv5 we had to wrap every Route we used with Sentry, so that's why I ask

**Comment by jasikpark** [comment]
> Yup the single wrapper is enough for us to make the routing work!

oooh cool maybe I can make a callout in the docs about that then?

**Pull request merged**
