### PR TITLE
Update CLI docs for new subcommands extracted from old subcommands

### PR DESCRIPTION
**Pull request by entretechno-jeremiah**
See <https://github.com/getsentry/sentry-cli/pull/1178>.

### CODE REVIEW

**Comment by kamilogorek** [comment]
Thanks @entretechno-jeremiah, we are still discussing how to approach this, while preserving information about `1.x` releases. Thanks for the contribution, will keep that PR open for now.

**Comment by kamilogorek** [comment]
Thanks @entretechno-jeremiah, we are still discussing how to approach this, while preserving information about `1.x` releases. Thanks for the contribution, will keep that PR open for now.

**Comment by shanamatthews** [comment]
@kamilogorek - This PR is still relevant, right?

It seems like we haven't gotten around to figuring out a way to keep versioned docs. Do you have any thoughts on priority for this?

**Comment by kamilogorek** [comment]
Current docs are fully backwards compatible, so it's not a burning matter, but I'd love to have versioned docs at one point for sure.

**Pull request closed without merging**
