### PR TITLE
feat: Update JS docs to use top level `tracePropagationTargets`

### PR DESCRIPTION
**Pull request by AbhiPrasad**
ref https://github.com/getsentry/sentry-javascript/issues/8352

Can only be merged after https://github.com/getsentry/sentry-docs/pull/7176 is merged in and https://github.com/getsentry/sentry-javascript/pull/8399 is released.

### CODE REVIEW

**Review by shanamatthews — COMMENTED** [review]
Should this change also have been made in src/platform-includes/performance/configure-sample-rate/javascript.electron.mdx and src/platform-includes/performance/configure-sample-rate/javascript.vue.mdx ?

**Comment by AbhiPrasad** [comment]
`src/platform-includes/performance/configure-sample-rate/javascript.electron.mdx` can only be updated when electron makes a release as has a separate release lifecycle than the rest of the js sdks - but good call on `src/platform-includes/performance/configure-sample-rate/javascript.vue.mdx`, will update.

**Comment by shanamatthews** [comment]
Perf - nothing else from the docs side on this in that case 😄

**Review by shanamatthews — APPROVED** [review]

**Review by Lms24 — APPROVED** [review]

**Comment by AbhiPrasad** [comment]
Release has been out for 2 weeks, so merging in now https://github.com/getsentry/sentry-javascript/releases/tag/7.57.0

**Pull request merged**
