### PR TITLE
Removed metrics documentation for .NET

### PR DESCRIPTION
**Pull request by jamescrosswell**
## DESCRIBE YOUR PR

Removing Metrics documentation now this feature has been deprecated

## IS YOUR CHANGE URGENT?  

Help us prioritize incoming PRs by letting us know when the change needs to go live.
- [ x ] None: Not urgent, can wait up to 1 week+

## SLA

- Teamwork makes the dream work, so please add a reviewer to your PRs.

@bruno-garcia you're the only person that I can assign as a reviewer on this sorry... I can't select Bryce in this repo.

## PRE-MERGE CHECKLIST

*Make sure you've checked the following before merging your changes:*

- [ ] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs (subject matter experts)
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

### CODE REVIEW

**Comment by jamescrosswell** [comment]
I see, the linting error implies this can't be removed for .NET in isolation (it would need to be removed for all the other platforms as well presumably?):

```
❌ Found 1 404 across 1 page

🌐 http://localhost:3000/product/explore/metrics/metrics-set-up
    - [.NET](/platforms/dotnet/metrics/)
```

**Comment by coolguyzone** [comment]
@bitsandfoxes can you take a look?

**Review by bitsandfoxes — APPROVED** [review]

**Comment by jamescrosswell** [comment]
> We can also remove the reference to the deleted page here
> 
> https://github.com/getsentry/sentry-docs/blob/10cd1e76c27538315259cb3240274755b1268948/docs/product/explore/metrics/metrics-set-up.mdx?plain=1#L17

Yeah I assumed that was the language agnostic docs though so would affect all the SDKs (not just the .NET SDK)... and I didn't want to mess with that.

**Comment by jamescrosswell** [comment]
> I think it's fine to remove the entry on the product page as it links specifically to the page that' getting removed.

Ah I see.. there's a link per platform. Thanks @bitsandfoxes

**Review by bitsandfoxes — APPROVED** [review]

**Pull request merged**
