### PR TITLE
docs: improve Nx CLI docs

### PR DESCRIPTION
**Pull request by meeroslav**
## DESCRIBE YOUR PR
*Tell us what you're changing and why. If your PR **resolves an issue**, please link it so it closes automatically.*

## IS YOUR CHANGE URGENT?  

Help us prioritize incoming PRs by letting us know when the change needs to go live.
- [ ] Urgent deadline (GA date, etc.): 
- [ ] Other deadline: 
- [ ] None: Not urgent, can wait up to 1 week+

## SLA

- Teamwork makes the dream work, so please add a reviewer to your PRs.
- Please give the docs team up to 1 week to review your PR unless you've added an urgent due date to it.
Thanks in advance for your help!

## PRE-MERGE CHECKLIST

*Make sure you've checked the following before merging your changes:*

- [ ] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs (subject matter experts)
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## LEGAL BOILERPLATE

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

## EXTRA RESOURCES

- [Sentry Docs contributor guide](https://docs.sentry.io/contributing/)

### CODE REVIEW

**Comment by AbhiPrasad** [comment]
Hey @meeroslav thanks for the PR.

I think we intended these docs to only be used with Angular use cases, hence the title being like that. @Lms24 thoughts on changing this?

**Review by Lms24 — APPROVED** [review]
Hey @meeroslav 👋 

Thanks for opening the PR! I think changing this is fine and calls things by their proper name. Since we're showing this only in Angular anyway.

**Comment by Lms24** [comment]
@meeroslav would you mind rebasing the PR to the latest commit on `master`? We had some CI changes in docs last week and I can't merge the PR because a job that no longer exists is marked as required.

**Comment by Lms24** [comment]
heads-up: I rebased the branch to get rid of the pending CI job. Should get merged soon!

**Pull request merged**
