### PR TITLE
Add 5 custom canonical tags based on SEO agency recs

### PR DESCRIPTION
**Pull request by coolguyzone**
## DESCRIBE YOUR PR
See the unchecked rows of https://docs.google.com/spreadsheets/d/1_V8fwvomASiJgXSD4LusD9JrOLZjIG_iCUnvXK3eF2o/edit?usp=sharing for the request.

To verify:
visit: https://sentry-docs-git-more-canonicals.sentry.dev/platforms/javascript/guides/cordova/data-management/sensitive-data/

Inspect and you will see that the canonical tag points to: https://docs.sentry.io/platforms/javascript/guides/koa/data-management/sensitive-data/  as referenced in the spreadsheet.

All five of these link will follow the same behavior.

## IS YOUR CHANGE URGENT?  

Help us prioritize incoming PRs by letting us know when the change needs to go live.
- [ ] Urgent deadline (GA date, etc.): 
- [ ] Other deadline: 
- [x] None: Not urgent, can wait up to 1 week+

## SLA

- Teamwork makes the dream work, so please add a reviewer to your PRs.
- Please give the docs team up to 1 week to review your PR unless you've added an urgent due date to it.
Thanks in advance for your help!

## PRE-MERGE CHECKLIST

*Make sure you've checked the following before merging your changes:*

- [ ] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs (subject matter experts)
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## LEGAL BOILERPLATE

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

## EXTRA RESOURCES

- [Sentry Docs contributor guide](https://docs.sentry.io/contributing/)

### CODE REVIEW

**Review by chargome — APPROVED** [review]
LGTM!

Apparently there is a 404 introduced with this pr which I find weird since you did not change any links – could you still have a look? There is a github action pointing you to the correct page in this pr

**Comment by a-hariti** [comment]
I faced the same on another PR @charliemday 

probably a bug, but I didn't get why it's happening as the url works when I click on it locally 🤔

**Comment by coolguyzone** [comment]
> LGTM!
> 
> Apparently there is a 404 introduced with this pr which I find weird since you did not change any links – could you still have a look? There is a github action pointing you to the correct page in this pr

This one's a bit of a mystery to me, all I did here was update some frontMatter data on a few markdown files, I double-checked the syntax, I'm not sure why it would be throwing a 404 on `/api/auth/`

**Comment by chargome** [comment]
@coolguyzone this was fixed in https://github.com/getsentry/sentry-docs/pull/11742, just rebase your pr on master

**Comment by coolguyzone** [comment]
Ah, thanks @chargome

**Pull request merged**
