### PR TITLE
feat: New platform layout and JavaScript conversion

### PR DESCRIPTION
**Pull request by dcramer**
image

### CODE REVIEW

**Comment by dcramer** [comment]
Will update README to detail how this works and (at least) fully convert Python before we merge this.

**Comment by dcramer** [comment]
I think we're in a good spot. I documented the layout in README.md, so you should treat that as the source of truth. If it doesnt make sense please leave feedback, as thats the only description you're getting.

This converts JavaScript only, as this layout doesn't really work with our historical "describe everything techincally" approach.

We ideally would have breadcrumbs in place before merging this.

**Comment by dcramer** [comment]
Also, needless to say this includes a bunch of unrelated things, including TypeScript.

**Comment by dcramer** [comment]
for anyone reviewer: ``src/gatsby/createPages.ts`` is the bulk of the work here

**Review by HazAT — APPROVED** [review]
I tried it out locally and it seems to work really well.
This is basically exactly what we envisioned for the new SDK docs 🥇 
I also like that we call it guides now, makes a lot of sense.

I skimmed over the code and couldn't find anything obvious so I approve this from a: "tried it locally and it works perspective".

**Comment by dcramer** [comment]
Breadcrumbs and logo are updated - will merge on green.

**Comment by dcramer** [comment]
image

**Pull request merged**
