### PR TITLE
Fixed a typo in routing-alerts.mdx

### PR DESCRIPTION
**Pull request by petarmaric**

### CODE REVIEW

**Comment by chadwhitacre** [comment]
Thanks @petarmaric! Looks like Vercel is borked, I'm _almost_ positive it's not your fault. ;-)

Let me see if that's an easy fix or if we should proceed here with some red ...

**Comment by petarmaric** [comment]
Hey @chadwhitacre, given my experience it may (somehow) be my fault. I'm known to be a very (un)desirable tester, able to break things just by looking at them funny :)

**Comment by chadwhitacre** [comment]
That is quite a useful skill to have! 😁

**Comment by chadwhitacre** [comment]
Merged! Might take a bit to show up on the site while we fix the Vercel issue. Thanks @petarmaric!

**Comment by petarmaric** [comment]
Anytime, glad to help any OSS project I can - but it's a special pleasure to make (even a small) mark in a wonderful project such as yours ;)

**Pull request merged**
