### PR TITLE
Remove 'Import Name' from python framework specific docs

### PR DESCRIPTION
**Pull request by EvanPurkhiser**
Many pthon docs have an italicized 'import name', however this doesn't add anything as immediately below this you can see the import in the code example. It just adds visual clutter

### CODE REVIEW

**Comment by untitaker** [comment]
I don't care for it as long as it's consistent with other sdks. There was some intent when starting with that. @mitsuhiko would know if anybody does.

**Comment by mitsuhiko** [comment]
I thought we had this for js too? I don’t have strong opinions on this for as long as people can find how to import the integration.

**Comment by EvanPurkhiser** [comment]
It makes sense here: https://docs.sentry.io/platforms/python/default-integrations/ (which is not where it's removed)

But on each individual integration you can immediately see it in the examples, which I would argue is where you would want to see what the module name is:

https://docs.sentry.io/platforms/python/flask/
https://docs.sentry.io/platforms/python/django/

**Comment by EvanPurkhiser** [comment]
We don't do this in javascript

**Comment by mitsuhiko** [comment]
The import names are listed on the JS page though: https://docs.sentry.io/platforms/javascript/?platform=rust

**Comment by EvanPurkhiser** [comment]
Sure, that's fine, as long as they're not immediately stuttered in code examples below :)

**Comment by untitaker** [comment]
@mitsuhiko opinions?

**Comment by mitsuhiko** [comment]
I don't have strong opinions on this. Seems fine either way.

**Pull request merged**
