### PR TITLE
Remove deprecated integrations from index

### PR DESCRIPTION
**Pull request by eurica**
I believe these integrations are gone (or in PD's case, not community/per-project)

Long term we should still restructure this whole section, but let's keep it true until then.

### CODE REVIEW

**Comment by MimiDumpling** [comment]
Thanks for getting this started, @eurica. 😊 I'll double check to see if any other integrations need removing from this list.

FYI, I'm currently creating a restructuring plan for Integrations and working with @jonesphillip on the project.

**Comment by MimiDumpling** [comment]
@jonesphillip will you double check the list of integrations we're removing? Pretty sure I got 'em all.

**Comment by MimiDumpling** [comment]
@eurica do you want the glory of the merge? 🏆

**Comment by eurica** [comment]
@MimiDumpling nope! send it out whenever works

**Pull request merged**
