### PR TITLE
feat(splunk): Add documentation for Splunk data forwarding

### PR DESCRIPTION
**Pull request by dcramer**

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
You can get some slightly better screenshots using [the "Capture node screenshot" chrome feature](https://developers.google.com/web/updates/2017/08/devtools-release-notes#node-screenshots). Specifically for the `splunk-data-forwarding-setting-complete.png` shot.

**Comment by dcramer** [comment]
@EvanPurkhiser actually going to ask someone to go over these in the future, because they dont have borders/etc, and it'd be ideal to do this under the new design

**Comment by dcramer** [comment]
(also, yet another use case for demokit!)

**Comment by dcramer** [comment]
Getting a first pass out the door so we can talk about it, but will follow up with polish once we get feedback

**Pull request merged**
