### PR TITLE
fix(cordova): fix docs around Cordova Perf and Profiling support

### PR DESCRIPTION
**Pull request by kahest**
mark Cordova not supported by browser profiling
fix Performance support (hide auto-instrumentation, custom init snippet,...)

### CODE REVIEW

**Review by lucas-zimerman — APPROVED** [review]
LGTM!

**Comment by bruno-garcia** [comment]
@kahest Nice change! 
Obviously not my call but I suggest we take a step further and remove the performance monitoring parts for cordova too.

Keeping it up-to-date with bug fixes etc makes sense but adding new things will introduce new use cases for us to debug

**Comment by bruno-garcia** [comment]
We also removed Session Replay from it

**Comment by lucas-zimerman** [comment]
> @kahest Nice change! Obviously not my call but I suggest we take a step further and remove the performance monitoring parts for cordova too.
> 
> Keeping it up-to-date with bug fixes etc makes sense but adding new things will introduce new use cases for us to debug

It's only the minimal docs for performance monitoring, the idea wasn't to add support to it, but to at least document a feature that already existed since 2021 https://github.com/getsentry/sentry-cordova/pull/216

**Comment by kahest** [comment]
> @kahest Nice change! Obviously not my call but I suggest we take a step further and remove the performance monitoring parts for cordova too.
> 
> Keeping it up-to-date with bug fixes etc makes sense but adding new things will introduce new use cases for us to debug

As @lucas-zimerman mentioned, this PR aims to add only the custom perf docs because that's what we've been supporting for a while, and we always mentioned supporting perf on the landing page of the SDK docs, but linked to generic product perf docs. In case we decided we don't support perf for Cordova, I'm all for not exposing it in the SDK and completely removing it from the docs. Wdyt?

**Review by krystofwoldrich — APPROVED** [review]

**Review by bruno-garcia — APPROVED** [review]
makes sense. thanks everyone

**Pull request merged**
