### PR TITLE
Update bundler plugin snippets to use new Debug ID process by default

### PR DESCRIPTION
**Pull request by lforst**
Waiting for the release of https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/204

Resolves https://github.com/getsentry/sentry/issues/47230

### CODE REVIEW

**Review by shanamatthews — APPROVED** [review]

**Comment by Jesse-Box** [comment]
By including this option, I think people will assume that it's related to releases because of the introduction text
> Sentry uses [releases](https://docs.sentry.io/product/releases/) to match the correct source maps to your events. You can use the Sentry esbuild plugin to automatically create releases and upload source maps to Sentry when bundling your app.
```javascript
sourcemaps: {
   // Specify the directory containing build artifacts
  assets: "./dist/**",
},
```

From my perspective, here are some requirements for this PR
- Users must understand that `sourcemap` option relates to a new method (artifact bundles + debug IDs) of un-minifying stack frames
- Users must understand what are the minimal versions required to use the new method (artifact bundles + debug IDs)
- Users must get a brief introduction to contextualize the different methods of un-minification

**Comment by lforst** [comment]
> By including this option, I think people will assume that it's related to releases because of the introduction text
> 
> > Sentry uses [releases](https://docs.sentry.io/product/releases/) to match the correct source maps to your events. You can use the Sentry esbuild plugin to automatically create releases and upload source maps to Sentry when bundling your app.

Good point. I removed the references to releases.

> From my perspective, here are some requirements for this PR
> 
> * Users must understand that `sourcemap` option relates to a new method (artifact bundles + debug IDs) of un-minifying stack frames
> * Users must understand what are the minimal versions required to use the new method (artifact bundles + debug IDs)
> * Users must get a brief introduction to contextualize the different methods of un-minification

Hm, I don't think these are requirements - 1 and 3 definitely aren't, so I wouldn't add them - just added text bloat. https://develop.sentry.dev/sdk/philosophy/#prioritize-customer-convenience-over-correctness

As for 2. I am just gonna ship this and see what the consequences are. We can add a note later.

**Comment by Jesse-Box** [comment]
# Vite (example)

In this guide, you'll learn how to successfully upload source maps using our vite bundler plugin.

## Introduction

You can use two methods of uploading source maps:
- Artifact Bundles (Preferred): Upload source maps whenever you need
- Release Bundles: Upload source maps when you create a new [Sentry release](https://docs.sentry.io/product/releases/)

> Uploading artifact bundles requires:
> - sentry-cli version >= `2.17.0`
> - Sentry Javascript SDK version >= `7.47.0`

## Installation

```npm
npm install @sentry/vite-plugin --save-dev
```

```yarn
yarn add @sentry/vite-plugin --dev
```

## Configuration

Learn more about configuring the plugin in our [Sentry Vite Plugin documentation](https://github.com/getsentry/sentry-javascript-bundler-plugins/tree/main/packages/vite-plugin).

Example:

```javascript {filename:vite.config.js}
import { defineConfig, loadEnv } from "vite";
import { sentryVitePlugin } from "@sentry/vite-plugin";

export default defineConfig(({ command, mode }) => {
  // Load env file based on `mode` in the current working directory.
  // Set the third parameter to '' to load all env regardless of the `VITE_` prefix.
  const env = loadEnv(mode, process.cwd(), "");
  return {
    build: {
      sourcemap: true, // Source map generation must be turned on
    },
    plugins: [
      // Put the Sentry vite plugin after all other plugins
      sentryVitePlugin({
        org: "___ORG_SLUG___",
        project: "___PROJECT_SLUG___",

        // Auth tokens can be obtained from https://sentry.io/settings/account/api/auth-tokens/
        // and need `project:releases` and `org:read` scopes
        authToken: env.SENTRY_AUTH_TOKEN,

        sourcemaps: {
          // Specify the directory containing build artifacts
          assets: "./dist/**",
        },

        // Optionally uncomment the line below to override automatic release name detection
        // release: env.RELEASE,
      }),
    ],
  };
});
```
> `sourcemaps.assets` is specific to uploading artifact bundles, and not release bundles

**Comment by lforst** [comment]
Thanks for the suggestion! I think this is still waaaay too confusing. As a naive user, I don't know what an artifact bundle is nor what a release bundle is. This is information they should just not care about.

**Comment by Jesse-Box** [comment]
@lforst I understand your point if the happy path of configuration works flawlessly. However, we know this flow isn't airtight. I'm concerned by providing this option without an explanation why it exists, people might assume their release bundle setup is broken because they've incorrectly configured this specific option.

**Comment by lforst** [comment]
i added a comment to the snippet what to do if theyre on an old version

**Comment by Jesse-Box** [comment]
You and your line comments... lol

I don't think a comment is sufficient if the default option is not going to work for 99.9% of users. We're also loosing an opportunity to 'upsell' them on upgrading their SDK.

**Comment by lforst** [comment]
I just want to get this out the door. Nothing is lost, nothing is permanent.

**Comment by Jesse-Box** [comment]
So if the goal is to literally update the snippets, then of course, the job is done. I just don't see the harm in expanding the scope of this a little to potentially clarify any unknowns from the users.

Am I over thinking this @AbhiPrasad @Lms24

**Comment by lforst** [comment]
The reason I think this is fine is because the code snippet is literally the only thing on the page users are guaranteed to look at. If they're not looking at the snippet, they didn't achieve anything at all. To me, the text surrounding the code snippet is just noise. I know, that as a developer I would ignore everything besides the snippet. That's why I acutally think it is the most prominent part of the page.

**Comment by lforst** [comment]
I'm shipping this because it is out in the bundler plugins and this PR doesn't hurt. Feel free to open a follow-up PR if necessary.

**Comment by AbhiPrasad** [comment]
I'm in favour of releasing the docs sooner rather than later so that we get as much adoption for debug ids as possible.

We can keep iterating on the specific language though, I'm in favour of highlighting the version requirements like you mentioned @Jesse-Box - the comment is not clear enough in my opinion, but this can come in follow up PRs!

**Pull request merged**
