### PR TITLE
fix: Arcade embeds fullscreen permission

### LINKED ISSUE #10462: Can't expand Arcade embeds to fullscreen
### Steps to Reproduce

- Open a docs page with an embedded Arcade, e.g.
  - https://docs.sentry.io/concepts/key-terms/tracing/trace-view/#product-walkthrough-trace-details-page
  - https://docs.sentry.io/concepts/data-management/event-grouping/#how-to-view-the-fingerprint
- press the expand to Fullscreen button in the upper right

### Expected Result

Arcade expands to fullscreen

### Actual Result

- Arcade stays at the same size
- slim black borders might appear around the Arcade
- error on the browser console
  - Chrome, Opera: `[Violation] Permissions policy violation: fullscreen is not allowed in this document.`
  - Safari: `Feature policy 'Fullscreen' check failed for element with origin 'https://demo.arcade.software' and allow attribute ''.`

### Additional Info

before pressing the button:
Screenshot 2024-06-21 at 16 04 06

after pressing the button: Screenshot 2024-06-21 at 16 04 14

### PR DESCRIPTION
**Pull request by a-hariti**
fixes #10462

### CODE REVIEW

**Comment by kahest** [comment]
@a-hariti not sure if this should work in the Vercel preview, but I reproduced the steps in https://github.com/getsentry/sentry-docs/issues/10462 and got similar results:
- Safari: `[Error] Feature policy 'Fullscreen' check failed for element with origin 'https://demo.arcade.software' and allow attribute 'clipboard-write'.`
  - note it now says `allow attribute 'clipboard-write'` instead of `allow attribute ''` 
  - maybe related error on pageload: `[Error] Blocked a frame with origin "https://sentry-docs-git-arcarde-fullscreen-permission.sentry.dev" from accessing a frame with origin "https://demo.arcade.software". Protocols, domains, and ports must match.`
- Chrome: `[Violation] Permissions policy violation: fullscreen is not allowed in this document.`
  - maybe related error on pageload: `Refused to frame 'https://vercel.live/' because it violates the following Content Security Policy directive: "frame-src demo.arcade.software player.vimeo.com".`

**Comment by a-hariti** [comment]
It should be good to go now @kahest

**Comment by kahest** [comment]
@a-hariti yep, now it works, thanks! I can approve the PR for functionality, but somebody else should probably take a look wrt the implementation

**Review by kahest — APPROVED** [review]

**Review by vivianyentran — APPROVED** [review]
Nice! Thanks for fixing this!

**Review by Jeffreyhung — APPROVED** [review]

**Pull request merged**
