### PR TITLE
fix: show header icons on hover and wrap the whole headers in links

### LINKED ISSUE #9218: Anchors for headings
Currently, the icon for the anchor link is always visible, but was previously only visible on hover, and the link only wraps the icon, not the whole headline anymore.

now:
Image

before (default state):
Image

before (on hover):
Image

### PR DESCRIPTION
**Pull request by a-hariti**
## Pre-merge checklist

*If you work at Sentry, you're able to merge your own PR without review, but please don't unless there's a good reason.*

- [ ] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## Description of changes

This PR closes #9218 

## Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

## Extra resources

- [Sentry Docs contributor guide](https://docs.sentry.io/contributing/)

### CODE REVIEW

**Comment by mjq-sentry** [comment]
@a-hariti Looks like the Vercel build is erroring on this change. I'm not sure if you're able to access the build error on Vercel, but it's:

```
15:03:46.324 | ReferenceError: options is not defined
15:03:46.324 | at /vercel/path0/.next/server/app/changelog/[slug]/page.js:1:15741
15:03:46.333 |  
15:03:46.333 | > Build error occurred
15:03:46.335 | Error: Failed to collect page data for /changelog/[slug]
15:03:46.335 | at /vercel/path0/node_modules/next/dist/build/utils.js:1217:15 {
15:03:46.335 | type: 'Error'
15:03:46.335 | }
```

**Comment by a-hariti** [comment]
There's some duplication on the `rehypePlugins` config.

I made it wok on the `mdx.ts` and did a copy paste to `mdxOptions.js` and missed it :\. I should've built locally first.

Pushing a fix now

**Comment by a-hariti** [comment]
I see that it's failing again but sadly I can't see the Vercel logs

**Review by stephanie-anderson — APPROVED** [review]
LGTM!

**Pull request merged**
