### PR TITLE
Switch to declarative labels

### PR DESCRIPTION
**Pull request by chadwhitacre**
cf. https://github.com/getsentry/sentry/pull/36833

### CODE REVIEW

**Comment by chadwhitacre** [comment]
Quick seatbelt:

```
$ cat .github/labels.yml | grep '\- name' | wc -l
      80
$
```

Also seeing 80 in [the UI](https://github.com/getsentry/sentry-docs/labels):

Screenshot 2023-04-28 at 4 26 40 PM

Ftr I fetched with (note `per_page`):

```
curl 'https://api.github.com/repos/getsentry/sentry-docs/labels?per_page=200' > labels.json
```

And I transmogrified with:

```python
#!/usr/bin/env python3
import json, yaml

labels_in = json.load(open(f'labels.json'))
labels_out = []
for label in labels_in:
    labels_out.append({
        'name': label['name'],
        'aliases': [],
        'color': label['color'],
        'description': label['description'],
    })

fp = open('.github/labels.yml', 'w+')
yaml.dump(labels_out, fp, sort_keys=False)
```

I don't like the look of that [comment](https://github.com/getsentry/sentry-docs/pull/6772#issuecomment-1528050497), though ... 🤔

**Comment by chadwhitacre** [comment]
Comment looking better, not sure if due to 8f577fb2a5a8ea07eb3b85d4d8b0a54dea94b7e1 (likely?) or 6db7cf4fd3923b0f1000d3fb580dd409ebfe6450. Testing with 8637f5c6cde35189e64aed44ca6cd4af3a16be2a ...

**Comment by chadwhitacre** [comment]
I think we're good. 👍

**Review by hubertdeng123 — APPROVED** [review]
Looks good to me, `sync-labels.yml` is the same as we use in sentry and the dry run won't change current labels

**Review by mattgauntseo-sentry — APPROVED** [review]

**Pull request merged**
