### PR TITLE
feat: Giscus comments based on GH discussions

### PR DESCRIPTION
**Pull request by a-hariti**
enable users to login with GH account and leave comments on docs,

which will show up under the repo discussions and on the docs page ofc.

Setup guide: https://giscus.app: basically install the Giscus app and enable Discussions

Currently I have it setup to my [personal fork](https://github.com/a-hariti/sentry-docs) for the preview

TODO:
- [ ] Point to actual repo
- [ ] Adjust to dark mode when dark mode PR is merged
- [ ] is the pathname -> discussion mapping enough given the dev docs/user docs situation?

### CODE REVIEW

**Review by Jeffreyhung — CHANGES_REQUESTED** [review]
@a-hariti we have a commitment to all of our public facing websites that we do not use any sort of tracking technology to track users and does not drop cookies other than the one we listed [here](https://sentry.io/cookiebounty/#essential-cookies). 
Can you provide some insights on if Giscus will track users or drop any cookies?

**Comment by a-hariti** [comment]
Does that include iframes @Jeffreyhung ?

**Comment by Jeffreyhung** [comment]
@a-hariti iframe is a common way that drops 3rd party cookies, but it doesn't necessary do so

**Comment by a-hariti** [comment]
It does drop these cookies, the question is does the no cookie policy cover iframes or not?

cookies from giscus.app

**Comment by a-hariti** [comment]
Cancelling this due to cookie policy

**Pull request closed without merging**
