### PR TITLE
feat(js): Update docs for custom integrations

### PR DESCRIPTION
**Pull request by mydea**
This updates the JS custom integration docs to show which APIs we support.

### CODE REVIEW

**Review by Lms24 — APPROVED** [review]
Great improvement! Should we also document `preprocessEvent` and `afterAllSetup`?

**Comment by mydea** [comment]
> I decided to keep it simple for now, not showing `preprocessEvent` and `afterAllSetup` because it probably should not be used in user-land (we can always add it later if needed).

I decided to keep it simple for now, not showing preprocessEvent and afterAllSetup because it probably should not be used in user-land (we can always add it later if needed). 

No strong feelings on this though, also happy to add this too 🤔

**Review by andreiborza — APPROVED** [review]

**Comment by andreiborza** [comment]
> > I decided to keep it simple for now, not showing `preprocessEvent` and `afterAllSetup` because it probably should not be used in user-land (we can always add it later if needed).
> 
> I decided to keep it simple for now, not showing preprocessEvent and afterAllSetup because it probably should not be used in user-land (we can always add it later if needed).
> 
> No strong feelings on this though, also happy to add this too 🤔

I'm personally interested in `afterAllSetup` since I'm using it atm :)

**Comment by mydea** [comment]
> I'm personally interested in afterAllSetup since I'm using it atm :)

haha, good point - I'll simply add all methods then 👍

**Comment by mydea** [comment]
Updated this to now document _all_ methods.

**Review by andreiborza — APPROVED** [review]
thanks!

**Pull request merged**
