### PR TITLE
build(nokogiri): Security upgrade for nokogiri

### PR DESCRIPTION
**Pull request by BYK**

### CODE REVIEW

**Comment by cameronmcefee** [comment]
I'll investigate. Most of it is style guide violations but I see actual test errors that need debugging.

**Comment by cameronmcefee** [comment]
Ok, this is actually failing during the build, so the tests are running on empty data. You can see the error by running `bin/server --trace`. It looks like something that got updated includes a breaking change. Looks to be somewhere in jekyll-assets, which tends to be aggravatingly fragile.

**Comment by cameronmcefee** [comment]
This is introducing more issues than I can presently take the time to troubleshoot.

**Comment by BYK** [comment]
@cameronmcefee I'll take a look at this later on.

**Comment by joshuarli** [comment]
Closing; not applicable anymore.

**Pull request closed without merging**
