### PR TITLE
Document time_spent core event attribute

### PR DESCRIPTION
**Pull request by nateberkopec**
This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry-docs/67)

### CODE REVIEW

**Comment by dcramer** [comment]
@nateberkopec I think we decided to just kill this for now until we actually have features around perf. Originally it was intended to be the "duration of this event" (so you could capture an issue that is duration based).

**Comment by nateberkopec** [comment]
@dcramer `site` is also undocumented, what's that supposed to do?

**Comment by dcramer** [comment]
@nateberkopec ``site`` is a deprecated attributed that we have more or less killed. It was a Django thing.

**Comment by nateberkopec** [comment]
👍

**Pull request closed without merging**
