### PR TITLE
Fix opengraph settings

### LINKED ISSUE #9485: Add an opengraph image to docs repo
### Problem Statement

Right now if you post the docs URL on social media no image is generated.

Screenshot 2024-03-18 at 3 21 02 PM

### Solution Brainstorm

Add the below open graph image in docs so that when we post a docs URL on social media it looks more eye-catching.

Screenshot 2024-03-18 at 3 25 22 PM

(This is what it looks like for the Sentry url, which does have an open graph image)

Screenshot 2024-03-18 at 3 23 55 PM

Here's an article about [open graph](https://www.semrush.com/blog/open-graph/).

### PR DESCRIPTION
**Pull request by a-hariti**
## Pre-merge checklist

*If you work at Sentry, you're able to merge your own PR without review, but please don't unless there's a good reason.*

- [ ] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## Description of changes

- I borrowed title & description from Sentry.io
- adapted the illustration from the new design to the recommended dimensions (1200x630)
- added possibility to see og image on preview deployments

Closes #9485

### CODE REVIEW

**Comment by a-hariti** [comment]
Do we have a higher resolution of the illustration @lizokm?

Also what do you thin about title & description?

**Comment by HazAT** [comment]
@a-hariti updated the title and made the image smaller (filesize)

**Comment by a-hariti** [comment]
Thank @HazAT 

The file size is not an issue on og images as the social bots don't care

Aspect ratio is though, I'm not sure if the image you used has the proper dimensions

**Comment by lizokm** [comment]
@a-hariti @HazAT aspect ration looks good to me in preview. I'm going to go ahead and merge.

**Pull request merged**
