### PR TITLE
ref(serverless): Improve serverless wizard slugs

### PR DESCRIPTION
**Pull request by EvanPurkhiser**
As far as I can tell, there's no need for this prefix like this. I'll update in the product as well

### CODE REVIEW

**Review by untitaker — APPROVED** [review]

**Review by ajjindal — COMMENTED** [review]
@EvanPurkhiser appending at the end may get cut off during display on UI. I liked how you had it prefixed before. However, if the UI shows well, we are good

**Comment by EvanPurkhiser** [comment]
I'll fix in the UI

**Comment by EvanPurkhiser** [comment]
This is a bit more consistent with what we had done before.

**Pull request merged**
