### PR TITLE
Remove Java SDK metrics docs

### PR DESCRIPTION
**Pull request by adinauer**
Removes metrics docs as metrics API has been removed in Java SDK v8.

## DESCRIBE YOUR PR
*Tell us what you're changing and why. If your PR **resolves an issue**, please link it so it closes automatically.*

## IS YOUR CHANGE URGENT?  

Help us prioritize incoming PRs by letting us know when the change needs to go live.
- [ ] Urgent deadline (GA date, etc.): 
- [ ] Other deadline: 
- [ ] None: Not urgent, can wait up to 1 week+

## SLA

- Teamwork makes the dream work, so please add a reviewer to your PRs.
- Please give the docs team up to 1 week to review your PR unless you've added an urgent due date to it.
Thanks in advance for your help!

## PRE-MERGE CHECKLIST

*Make sure you've checked the following before merging your changes:*

- [ ] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs (subject matter experts)
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## LEGAL BOILERPLATE

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

## EXTRA RESOURCES

- [Sentry Docs contributor guide](https://docs.sentry.io/contributing/)

### CODE REVIEW

**Comment by coolguyzone** [comment]
Hi @adinauer , I think we need to add some redirects here as these pages are being indexed by google and there may be some other external links out there. Do you know where you'd like these pages to redirect to? If you're comfortable with it, you can add the redirects to this PR yourself, here's a pretty straightforward example: https://github.com/getsentry/sentry-docs/pull/11861/files

Otherwise we can add the redirects, just let me know where to point them. Thanks!

**Review by coolguyzone — CHANGES_REQUESTED** [review]
See comment about redirects.

**Comment by adinauer** [comment]
Thanks, I'll try to find out, where we want to redirect to.

**Comment by adinauer** [comment]
Talked to the team and there's a link to https://sentry.zendesk.com/hc/en-us/articles/26369339769883-Metrics-Beta-Ended-on-October-7th on the [python docs](https://docs.sentry.io/platforms/python/metrics/). That page explains why we ended the metrics beta.

I'll update the PR to include the redirect.

**Comment by adinauer** [comment]
I just talked to @stephanie-anderson and we decided we're gonna keep things as they are.
The metrics pages are hidden in the sidebar and there's a disclaimer on top linking to the zendesk page above in case someone still visits the pages.
I'm closing this PR.

**Pull request closed without merging**
