### PR TITLE
Create structure for Performance content to be common across all platforms

### PR DESCRIPTION
**Pull request by PeloWriter**
Note: This PR enables common content for JavaScript (and its guides) as well as React Native. A later PR will enable the common performance content for Go, Python, and PHP.

This is a WIP, the following includes (primarily appropriate code samples) need to be built for React Native:
- Getting Started (index.mdx)
  - includes/performance/install-tracing-package
  - includes/performance/configure-tracing package

- Grouping Transactions (group-transactions.mdx)
  - includes/performance/group-transaction-example

- Manual Instrumentation (manual.mdx)
  - includes/performance/enable-manual-instrumentation
  - includes/performance/manual-instrumentation-example

- Retrieve an Active Transaction (retrieve-active-transaction.mdx)
  - includes/performance/retrieve-transaction

- Connecting Frontend and Backend Transactions
 - no include needed; this is unsupported by React Native at this time

- Control Data Truncation (add-to-spans.mdx)
  - includes/performance/control-data-truncation

- Automatic Instrumentation (automatic.mdx)
  - includes/performance/enable-automatic-instrumentation
  - includes/performance/tracingOrigins-example
  - includes/performance/beforeNavigate-example
  - includes/performance/filter-span-example

### CODE REVIEW

**Comment by bruno-garcia** [comment]
@PeloWriter The snippets can be added in this PR, right? So @jennmueng could contribute here?

**Comment by PeloWriter** [comment]
Yes, @bruno-garcia - adding here is fine.

**Comment by jennmueng** [comment]
We want to get barebones docs for manual instrumentation out first as everything else is waiting on https://github.com/getsentry/sentry-react-native/pull/1230.

Nothing needs to be installed as tracing is already included with the React Native SDK, the configuration would be a little different, and manual instrumentation works exactly the same on react native as on javascript, but maybe a React-component-specific example might be a good addition.

So if I understand this correctly I would just add `react-native.mdx` files in the includes folder? If that's right I'll get to work.

**Comment by PeloWriter** [comment]
Yes, if you populate the directories noted with react-native.mdx files we'll be good to go.

**Pull request merged**
