### PR TITLE
Add docs for beforeSendTransaction in Java

### PR DESCRIPTION
**Pull request by adinauer**
Docs for filtering transactions via `beforeSendTransaction`

https://github.com/getsentry/sentry-java/issues/2358

### CODE REVIEW

**Comment by adinauer** [comment]
@romtsn just discussed with team. There's some PR(s) going on around restructuring. It's fine to add where others placed it for now as it'll be moved anyways.

**Review by romtsn — APPROVED** [review]

**Comment by lizokm** [comment]
I'll also take a look at this today @romtsn, @adinauer.

**Comment by adinauer** [comment]
@lizokm do you still plan on giving this a review or can I go ahead and merge?

**Review by antonpirker — APPROVED** [review]

**Comment by adinauer** [comment]
Merging now, if there's any feedback, just let me know, I can send another PR to improve.

**Pull request merged**
