### PR TITLE
add hint to Symfony configuration

### PR DESCRIPTION
**Pull request by SchmidtClaudia**
## Pre-merge checklist

*If you work at Sentry, you're able to merge your own PR without review, but please don't unless there's a good reason.*

- [ ] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## Description of changes

I added a short note incl. link to the Symfony configuration options. For my point of view this makes it easier to find how to add a tag in a Symfony environment.

### CODE REVIEW

**Comment by lizokm** [comment]
@cleptric Would really appreciate it if you could take a look at this!

**Review by cleptric — CHANGES_REQUESTED** [review]
This should only be visible in the Symfony docs. A code example would help as well.

**Comment by SchmidtClaudia** [comment]
I try to update next week. Any hint on how I can only update the symfony docs?

**Comment by SchmidtClaudia** [comment]
I moved the hint to the Symfony docs and added an example. Not sure if it works cause I have no preview.

**Review by cleptric — APPROVED** [review]

**Comment by cleptric** [comment]
Thanks!

**Pull request merged**
