### PR TITLE
feat: Improve algolia search results

### PR DESCRIPTION
**Pull request by chargome**
- Applies custom search settings from `sentry-global-search`
- Tags algolia records with their respective sdk and framework names for improving path bias (when searching from react guide, results will prioritise records within the guide)
- Updates search settings for algolia client to include framework name for improving search results

relates to [#10592](https://github.com/getsentry/sentry-docs/issues/10592)

### CODE REVIEW

**Comment by a-hariti** [comment]
Does it address this example from the mentioned issue by @mydea ?

Opentelementry search while on node platform

**Review by a-hariti — COMMENTED** [review]
I like this idea!

**Comment by chargome** [comment]
@a-hariti yes it does improve the search for that case. Generally speaking, the path bias makes search much more usable this way, but there is probably still room for improvement. Let's try to gather cases and improve incrementally I would say

**Comment by a-hariti** [comment]
is this preview using test indices with tagged records?

**Comment by chargome** [comment]
No the preview is still running on the old index. You can only test that out with a local version of sentry-global-search

**Comment by a-hariti** [comment]
I understand, so you can only test the ranking locally?

**Comment by chargome** [comment]
Yes, or through the dashboard on algolia

**Review by lforst — APPROVED** [review]

**Pull request merged**
