### PR TITLE
ref(error-tracing): remove due to automation

### PR DESCRIPTION
**Pull request by doralchan**
Removes https://docs.sentry.io/product/sentry-basics/guides/error-tracing/

### CODE REVIEW

**Comment by dashed** [comment]
@doralchan It might be a good idea to add a redirect for this route.

**Comment by doralchan** [comment]
We don't have one yet @dashed

**Comment by dashed** [comment]
@doralchan I think that'll be the next best page. I think this is how the redirect will be setup: https://docs.sentry.io/contributing/pages/redirects/

**Comment by doralchan** [comment]
Note: The marketing link that went to error-tracking has been updated (https://docs.sentry.io/product/performance/distributed-tracing/)

**Comment by dashed** [comment]
@doralchan It links to https://docs.sentry.io/product/performance/getting-started/ in https://github.com/getsentry/static-sites/commit/413b45c713e4aa527e1e27b6988e7c2c70bddee5 . Just in case if this was intended.

**Review by dashed — APPROVED** [review]
👍 👍 👍

**Pull request merged**
