### PR TITLE
Update information about ignore_logger usage

### PR DESCRIPTION
**Pull request by jaysonsantos**

### CODE REVIEW

**Comment by untitaker** [comment]
That's not true though. The moment you call `ignore_logger` the logger is ignored, it has nothing to do with `init()`. What is the actual behavior you are seeing?

**Comment by jaysonsantos** [comment]
Hey there, I guess you are right.
Trying to isolate the problem I found out that it won't ignore the children of root's logger.
If I ignore the root e.g. `test` it does not mean that `test.child` would be ignored.
From that, I thought that the problem was with the ordering but it was with the children.

**Comment by jaysonsantos** [comment]
Hey there @untitaker, do you think that it is important to document that if you ignore the root logger it does not mean that the children will also be ignored?

**Comment by untitaker** [comment]
Do you want to make a pr? Otherwise I'll do one later

**Pull request closed without merging**
