### PR TITLE
Revisit Android sidebar

### PR DESCRIPTION
**Pull request by stefanosiano**
## Pre-merge checklist

*If you work at Sentry, you're able to merge your own PR without review, but please don't unless there's a good reason.*

- [ ] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## Description of changes

removed video tutorial, as probably outdated
added new section Enhance Error Reporting
moved kotlin compiler plugin, proguard and source context under Enhance Error Reporting section
moved NDK and Gradle under Configuration

## Extra resources

- [Sentry Docs contributor guide](https://docs.sentry.io/contributing/)

### CODE REVIEW

**Review by shanamatthews — COMMENTED** [review]
Could you add redirects for all pages that were moved/deleted?
We don't want to break external links either 😄

**Comment by stefanosiano** [comment]
> Could you add redirects for all pages that were moved/deleted? We don't want to break external links either 😄

yeah, i already added a redirect for all pages
the only missing one is the android-video, which was deleted. I'm not sure what to do with it

**Comment by shanamatthews** [comment]
> > Could you add redirects for all pages that were moved/deleted? We don't want to break external links either 😄
> 
> yeah, i already added a redirect for all pages the only missing one is the android-video, which was deleted. I'm not sure what to do with it

Thanks for adding those! I think we can just add a redirect to the Getting Started page (https://docs.sentry.io/platforms/android/). I added that to verce.json for ya.

**Review by shanamatthews — APPROVED** [review]

**Review by romtsn — APPROVED** [review]
nice work!

**Pull request merged**
