### PR TITLE
Changes based on updated terms for Session Replay

### PR DESCRIPTION
**Pull request by jas-kas**
See Notion page on this here - https://www.notion.so/sentry/Session-Replay-Lexicon-Style-Guide-bcbbd569e5fc41f2aaff2f7d796fd401

### CODE REVIEW

**Comment by jas-kas** [comment]
@ryan953 What's the easiest way to have this apply across all our SDK docs? 😅

**Review by bruno-garcia — APPROVED** [review]

**Comment by bruno-garcia** [comment]
> @ryan953 @bruno-garcia What's the easiest way to have this apply across all our SDK docs? 😅

Find and replace is the way to go

**Comment by jas-kas** [comment]
@lizokm LMK if these changes look good and I'll update this across all eligible platforms for Replay!

**Comment by jas-kas** [comment]
Closing due to conflicts.

**Pull request closed without merging**
