### PR TITLE
feat(org-tokens): Update remaining places to org auth token usage

### PR DESCRIPTION
**Pull request by mydea**
This updates remaining places in the docs to use/reference the new org tokens.

Please esp. review this with regards to mobile/native use cases, as I am not really versed in how stuff works that, but I _think_ this should work.

While at it, I also updated some places I found where we weren't using the `___ORG_SLUG___` and `___PROJECT_SLUG___` placeholders.

### CODE REVIEW

**Comment by adinauer** [comment]
@mydea I've created #7755 to suggest further improvements for the Java SDKs source context docs. Can you please review and merge this in here if you think it makes sense?

**Review by adinauer — APPROVED** [review]
LGTM 🚀

**Comment by shanamatthews** [comment]
Hey @mydea - sorry for the delay on this! I will review this PR tomorrow.

**Review by shanamatthews — APPROVED** [review]
Thanks for updating all of these @mydea !

I still think we need product docs explaining org auth tokens as well as our other token types. With this change the docs make it seem like org auth tokens are the *only* way to get tokens, especially in the CLI docs.

**Comment by mydea** [comment]
> Thanks for updating all of these @mydea !
> 
> I still think we need product docs explaining org auth tokens as well as our other token types. With this change the docs make it seem like org auth tokens are the _only_ way to get tokens, especially in the CLI docs.

Yeah, I'll try to write up some product docs in the near future explaining this. FWIW, I think for the places where this has bene replaced these tokens _are_ what people should use (there is no reason to use something else, really). But having a decent place explaining all of this (and the why, as well) def. makes sense 👍

**Pull request merged**
