### PR TITLE
Add SentryHttpMessageHandler docs for .NET

### LINKED ISSUE #3131: .NET: Document the usage of SentryHttpMessageHandler outside of ASP.NET Core
As mentioned here: https://github.com/getsentry/sentry-docs/pull/3121#discussion_r579460913

(Creating an issue so I don't forget)

### PR DESCRIPTION
**Pull request by Tyrrrz**
Closes #3131
Depends on #3121

### CODE REVIEW

**Comment by bruno-garcia** [comment]
@Tyrrrz needs rebasing?

**Review by bruno-garcia — COMMENTED** [review]
nice!

**Comment by Tyrrrz** [comment]
@bruno-garcia not sure what's the cause of the error :/

**Review by bruno-garcia — APPROVED** [review]
:shipit:

**Pull request merged**
