### PR TITLE
`enable_db_query_source` is now on by default

### PR DESCRIPTION
**Pull request by sentrivana**
## Pre-merge checklist

*If you work at Sentry, you're able to merge your own PR without review, but please don't unless there's a good reason.*

- [ ] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## Description of changes

We'll be changing the default for the `enable_db_query_source` Python SDK option from `False` to `True` in https://github.com/getsentry/sentry-python/pull/2629 -- updating the docs.

## Extra resources

- [Sentry Docs contributor guide](https://docs.sentry.io/contributing/)

### CODE REVIEW

**Comment by vivianyentran** [comment]
Can you update the note here as well? https://docs.sentry.io/product/performance/queries/#query-sources

**Comment by sentrivana** [comment]
@vivianyentran Updated!

**Review by AbhiPrasad — APPROVED** [review]

**Review by gggritso — APPROVED** [review]
👏🏻

**Review by vivianyentran — APPROVED** [review]
LGTM, thanks for updating!

**Review by shanamatthews — APPROVED** [review]

**Comment by sentrivana** [comment]
Thanks for the reviews, y'all -- will keep this open until we release the SDK that contains the change.

**Comment by sentrivana** [comment]
Closing in favor of https://github.com/getsentry/sentry-docs/pull/9014

**Pull request closed without merging**
