### PR TITLE
Inline related guides for frameworks

### LINKED ISSUE #6977: Right sidebar isn't visible on mobile
### Steps to Reproduce

Open docs on mobile or on small window size

### Expected Result

right sidebar exists somewhere to choose framework guides

### Actual Result

it doesn't

### Additional Info

this blocks mobile users or users who have docs in a small window from noticing or accessing framework-specific guides

### PR DESCRIPTION
**Pull request by natikgadzhi**
## Summary

This PR fixes #6977 by always displaying the list of related guides. Here's the video of how that looks: 

<div>
    <a href="https://www.loom.com/share/beeb90904d674b77823f4204cecdac2d">
      <p>Code Base Issue with Sentry Docs - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/beeb90904d674b77823f4204cecdac2d">
      
    </a>
  </div>

/cc @shanamatthews. I am not absolutely sure if this is the right approach — this does duplicate the list of guides in the main and right column, and does take a bit of space from the main column. So no hard feelings if we decide not to go in this direction. 

## Pre-merge checklist

*If you work at Sentry, you're able to merge your own PR without review, but please don't unless there's a good reason.*
- [x] Local linters are happy
- [ ] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## Description of changes

This PR changes `common/index.mdx` file, which makes it so that most platform pages that don't have their own `index.mdx`, would default to that. 

The actual change replaces the alert to see the list of framework-related guides in the right sidebar with the actual list of framework-related guides, inline. 

## Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

## Extra resources

- [Sentry Docs contributor guide](https://docs.sentry.io/contributing/)

### CODE REVIEW

**Comment by shanamatthews** [comment]
Hey, thanks @natikgadzhi !

I agree that this probably isn't the ideal fix. For example, JS has a lot of frameworks and the framework list takes the whole page:

Screenshot 2023-10-31 at 9 28 44 AM

I think the ideal fix would look more like what the Astro docs do: 

Screenshot 2023-10-31 at 9 35 44 AM

Adding a button with a dropdown list when the page width gets too small:

Screenshot 2023-10-31 at 9 35 19 AM

**Comment by natikgadzhi** [comment]
@shanamatthews, thank you for taking a look! Yep, I noticed that JavaScript page in this scenario is a disaster. 

I agree with you re: Astro approach. We have that already on Sentry docs site — in mobile layout, it'll show Table of Contents that toggles _left sidebar_:

Screenshot 2023-10-31 at 11 57 45 AM

A few things come to mind:
- It would be good to make whatever fix we will choose consistent. Some platforms have their own page, and some are inherited. **Using the menu toggle approach would solve this.**
- It would be good to make whatever items are in the right sidebar accessible, not just the list of frameworks. **Again, including items from the right sidebar in the toggled menu would solve the problem**.

What I could do is a quick experiment on adding the right sidebar items to that toggle. I'll push it up in a few hours.

**Comment by shanamatthews** [comment]
That sounds awesome - looking forward to it @natikgadzhi !

**Comment by natikgadzhi** [comment]
@shanamatthews uh oh! I took another look on overall navigation and media stops, here's what I see: https://www.loom.com/share/691d579857b34ed7a8091927249f12f1

I can try and write a summary / RFC on how to organize the navigation and menu behavior on smaller screens before I throw any code in the PR. If we align on that, the actual coding part is straightforward, and we get to fix the menu taking multiple lines and breaking the markup, and a few other small quirks "for free". 

Would you like me to start with a writeup? I can post that here, run by you, hopefully get a green light, and try to implement it.

**Comment by shanamatthews** [comment]
@natikgadzhi - wow, thanks for taking the time to look into all of this! These videos are great 😄 

If you want to write up a summary on how to organize the navigation that would be fantastic!

I will say that there's a good chance the docs site will get a rewrite in the next 6 months or so, BUT I think any work done to plan out a good UX for side bar behavior at different screen widths will be valuable and live on!

**Pull request closed without merging**
