### PR TITLE
feat(server): Remove dsym server docs

### PR DESCRIPTION
**Pull request by mitsuhiko**
These docs are no longer correct as it stands and the next version of sentry
will document symbolicator instead.

### CODE REVIEW

**Comment by cameronmcefee** [comment]
Should we do any redirecting?

**Comment by mitsuhiko** [comment]
We could in theory link to this repository: https://github.com/getsentry/symbolserver

**Comment by cameronmcefee** [comment]
Up to you, if you think this url is well trafficked enough.

**Comment by mitsuhiko** [comment]
I don't feel bad having this link turn into a 404. The native support on the release version of sentry for system symbols is already super hostile. I would like to instead make a better effort now that symbolicator is stable with the next oss release.

CC @BYK for context.

**Comment by cameronmcefee** [comment]
:+1: Merge when it suits you, looks good to me.

**Pull request merged**
