### PR TITLE
docs: add missing keys from sentry/sentry-symfony configuration reference

### PR DESCRIPTION
**Pull request by qkdreyer**

### CODE REVIEW

**Comment by dashed** [comment]
@Jean85 can you review this PR and see if it's good to merge?

**Comment by dashed** [comment]
@qkdreyer would you be able to add the note that @Jean85 mentioned to the doc somewhere?

**Comment by qkdreyer** [comment]
@dashed I’m not sure I’m following here. What do you want me to add and where ? 🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Jean85** [comment]
The options that are being added by this PR are available only since version 3.2.0 of `sentry/sentry-symfony`, that's what the note needs to say.

**Comment by qkdreyer** [comment]
Sorry for the delay, totally forgot that PR.

**Comment by dashed** [comment]
@qkdreyer No problem! Thanks for getting back to this PR 👍 

@Jean85 are the latest changes fine now?

**Pull request merged**
