### PR TITLE
Add missing line to Kotlin Multiplatform Docs

### PR DESCRIPTION
**Pull request by nathcakes**
## DESCRIBE YOUR PR
*Tell us what you're changing and why. If your PR **resolves an issue**, please link it so it closes automatically.* 

I was following the set-up for the Kotlin Multiplatform Docs and received an IDE error that SentryOptions needs to be imported. 

I've added the required line so that the documentation is correct.

## IS YOUR CHANGE URGENT?  

Help us prioritize incoming PRs by letting us know when the change needs to go live.
- [ ] Urgent deadline (GA date, etc.): 
- [ ] Other deadline: 
- [X] None: Not urgent, can wait up to 1 week+

## SLA

- Teamwork makes the dream work, so please add a reviewer to your PRs.
- Please give the docs team up to 1 week to review your PR unless you've added an urgent due date to it.
Thanks in advance for your help!

## PRE-MERGE CHECKLIST

*Make sure you've checked the following before merging your changes:*

- [ ] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs (subject matter experts)
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## LEGAL BOILERPLATE

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

## EXTRA RESOURCES

- [Sentry Docs contributor guide](https://docs.sentry.io/contributing/)

### CODE REVIEW

**Comment by lizokm** [comment]
@buenaflor could you take a look at this when you have a moment please?

**Review by buenaflor — COMMENTED** [review]
Looks good, thx for the catch @nathcakes

**Review by buenaflor — APPROVED** [review]

**Review by vivianyentran — APPROVED** [review]
Thanks for fixing this!

**Comment by vivianyentran** [comment]
@a-hariti Can you take a look into why this vercel sentry-docs deployment is failing?

**Comment by buenaflor** [comment]
@nathcakes could you merge main into your branch pls

**Comment by nathcakes** [comment]
@buenaflor Sorry about that! Merged now.

**Pull request merged**
