### PR TITLE
feat(develop): Clarify adding constraints

### PR DESCRIPTION
**Pull request by isabellaenriquez**
## DESCRIBE YOUR PR
Updates develop docs Database Migrations page to clarify the caveats for adding any type of constraint (as opposed to just not null).

### Adding Columns
image

###  Adding Not Null to Columns -> Adding Constraints to Columns (Including Not Null)
image

## IS YOUR CHANGE URGENT?  

Help us prioritize incoming PRs by letting us know when the change needs to go live.
- [ ] Urgent deadline (GA date, etc.): 
- [ ] Other deadline: 
- [x] None: Not urgent, can wait up to 1 week+

## PRE-MERGE CHECKLIST

*Make sure you've checked the following before merging your changes:*

- [ ] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs (subject matter experts)
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

### CODE REVIEW

**Review by vbro — APPROVED** [review]
LGTM
wait for owners-migrations before merging

**Comment by vbro** [comment]
FYI: https://www.postgresql.org/docs/current/sql-altertable.html#SQL-ALTERTABLE-NOTES

```
Scanning a large table to verify a new foreign key or check constraint can take a long time, and other updates to the table are locked out until the ALTER TABLE ADD CONSTRAINT command is committed ...
```

**Comment by isabellaenriquez** [comment]
@vbro thanks, this is covered in the section already:
> One approach is to create the constraint as not valid. Then we validate it afterwards. We still need to scan the whole table to validate, but we only need to hold a SHARE UPDATE EXCLUSIVE lock, which only blocks other ALTER TABLE commands, but will allow reads/writes to continue. This works well, but has a slight performance penalty of 0.5-1%. After Postgres 12 we can extend this method to add a real NOT NULL constraint.

**Review by vgrozdanic — APPROVED** [review]
looks good, thanks for updating the docs 🙌

**Review by wedamija — COMMENTED** [review]
Thanks for adding this - I'm wondering if we should considering just banning the positive integer fields as well. Either that, or modify them to validate the constraint afterwards without the statement timeout

**Comment by isabellaenriquez** [comment]
@wedamija We use them a lot on billing side for currency fields, so I'd lean towards the latter solution

**Pull request merged**
