### PR TITLE
Update supported platforms on index page w/ latest frameworks

### PR DESCRIPTION
**Pull request by benvinegar**
cc @getsentry/team

image

---
This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry-docs/51)

### CODE REVIEW

**Comment by benvinegar** [comment]
Current page: https://docs.sentry.io/hosted/

**Comment by macqueen** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry-docs/51)*

**Comment by dcramer** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry-docs/51)*

**Comment by dcramer** [comment]
:lgtm::lgtm::lgtm::lgtm::lgtm::lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry-docs/51#-:-KPZ4FVqte5I7G9kIMCz:b-i50kz7)*

**Pull request merged**
