### PR TITLE
Update troubleshooting.mdx - Add `DAY` when using `INTERVAL` while referencing the `SENTRY_RETENTION_DAYS` variable

### PR DESCRIPTION
**Pull request by waays-tl**
Add `DAY` in the `INTERVAL` keyword used to manually purge the nodestore_node table to prevent accidentally purging (almost) the entire table, since the days would be used as seconds.

## DESCRIBE YOUR PR

When manually purging events from the nodestore_node table, the example request in the documentation makes use of the `INTERVAL`  keyword, referencing the `$SENTRY_RETENTION_DAYS` variable, but without specifying the `DAY` keyword to `INTERVAL`, which can lead people to input days that will be interpreted as seconds by PostgreSQL.

## IS YOUR CHANGE URGENT?  

Help us prioritize incoming PRs by letting us know when the change needs to go live.
- [ ] Urgent deadline (GA date, etc.): 
- [ ] Other deadline: 
- [X] None: Not urgent, can wait up to 1 week+

## SLA

- Teamwork makes the dream work, so please add a reviewer to your PRs.
- Please give the docs team up to 1 week to review your PR unless you've added an urgent due date to it.
Thanks in advance for your help!

## PRE-MERGE CHECKLIST

*Make sure you've checked the following before merging your changes:*

- [ ] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs (subject matter experts)
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## LEGAL BOILERPLATE

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

## EXTRA RESOURCES

- [Sentry Docs contributor guide](https://docs.sentry.io/contributing/)

### CODE REVIEW

**Review by aldy505 — COMMENTED** [review]
The `DAY` could also be anything that day like, if they prefer months or even years. Perhaps we should also point people to the Postgres documentation on this one, so they'd be more aware of the query that they're executing? https://www.postgresql.org/docs/current/functions-datetime.html

**Comment by aldy505** [comment]
bump @joshuarli @hubertdeng123

**Comment by aldy505** [comment]
anyway, the stale label isn't removed when there's a new comment like this. so we should probably fix that?

**Comment by aldy505** [comment]
bump @joshuarli @hubertdeng123

**Comment by aldy505** [comment]
bump @joshuarli @hubertdeng123

**Comment by aldy505** [comment]
Meh, I'll just ping @BYK

**Review by BYK — APPROVED** [review]
I guess? 😅

**Pull request merged**
