### PR TITLE
Update java.spring-boot.mdx

### PR DESCRIPTION
**Pull request by jpomykala**
It ain't much, but it's honest work.

### CODE REVIEW

**Comment by imatwawana** [comment]
@getsentry/owners-native - nudge

**Review by Swatinem — APPROVED** [review]
just rubberstamping. Java / SpringBoot is not really a native team concern

**Comment by marandaneto** [comment]
@maciejwalkowiak Does the change make sense? thanks.

**Comment by imatwawana** [comment]
> @maciejwalkowiak Does the change make sense? thanks.

@maciejwalkowiak nudge 😄

**Comment by adinauer** [comment]
LGTM 😃

**Review by adinauer — APPROVED** [review]

**Pull request merged**
