### PR TITLE
fix(distr-tracing): Reintroduce distributed tracing sections

### PR DESCRIPTION
**Pull request by kahest**
supersedes #8624 

- ([Dart](https://sentry-docs-git-kahest-fix-missingdistr-tracing-docs.sentry.dev/platforms/dart/usage/distributed-tracing/custom-instrumentation/), [Rust](https://sentry-docs-git-kahest-fix-missingdistr-tracing-docs.sentry.dev/platforms/rust/usage/distributed-tracing/custom-instrumentation/), [Native](https://sentry-docs-git-kahest-fix-missingdistr-tracing-docs.sentry.dev/platforms/native/usage/distributed-tracing/custom-instrumentation/)) re-adds distributed tracing platform docs in the new docs structure under `Usage > Distributed Tracing`
- ([Flutter](https://sentry-docs-git-kahest-fix-missingdistr-tracing-docs.sentry.dev/platforms/flutter/usage/distributed-tracing/limiting-trace-propagation/)) splits out `Limiting Trace Propagation` snippet into separate menu item to follow new structure
	- there are still many other platforms where trace propagation targets are not part of distributed tracing docs, but rather e.g. in general configuration docs, but didn't want to include all that in this PR
- (Java) removes old/outdated and unused distributed tracing docs

### CODE REVIEW

**Comment by supervacuus** [comment]
Okay, thanks, that makes more sense. Do you think it might still be possible to link between 

```
Performance Monitoring 
  > Instrumentation 
    > Custom instrumentation 
```

and 

```
Sentry for Native
  > Usage
    > Distributed Tracing
      > Custom Instrumentation
```

or is that separation the ultimate goal here? I could imagine that people who use the performance monitoring API in the Native SDK might also be interested in where they can continue a trace. Search doesn't reveal anything on that topic, and manually, they'd have to search in another tree three levels deep.

I am not trying to be a pain here 😅

**Comment by kahest** [comment]
@supervacuus how about this https://github.com/getsentry/sentry-docs/pull/8842/files#diff-f04f8ba57495f2982ce8f614a1ba552ca3d0b95b1eb09cdec0fe9c6244aee43aR26 ([preview](https://sentry-docs-git-kahest-fix-missingdistr-tracing-docs.sentry.dev/platforms/native/performance/instrumentation/custom-instrumentation/#distributed-tracing))

**Comment by supervacuus** [comment]
> @supervacuus how about this https://github.com/getsentry/sentry-docs/pull/8842/files#diff-f04f8ba57495f2982ce8f614a1ba552ca3d0b95b1eb09cdec0fe9c6244aee43aR26 ([preview](https://sentry-docs-git-kahest-fix-missingdistr-tracing-docs.sentry.dev/platforms/native/performance/instrumentation/custom-instrumentation/#distributed-tracing))

That would work fine! Thx!

**Review by shanamatthews — APPROVED** [review]
I looked through everything and it looked really good. Thanks for taking the time to sort all of this out @kahest !

**Pull request merged**
