### PR TITLE
Added description about Google Oauth2 setup

### PR DESCRIPTION
**Pull request by pasha121**
## DESCRIBE YOUR PR
I tried to add google auth to my sentry self-hosted and got an error. I have googled a lot of time and finally find solution.
I would like to add it to docs
Thanks 
## IS YOUR CHANGE URGENT?  

Help us prioritize incoming PRs by letting us know when the change needs to go live.
- [x] None: Not urgent, can wait up to 1 week+

## SLA

- Teamwork makes the dream work, so please add a reviewer to your PRs.
- Please give the docs team up to 1 week to review your PR unless you've added an urgent due date to it.
Thanks in advance for your help!

## PRE-MERGE CHECKLIST

*Make sure you've checked the following before merging your changes:*

- [x] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs (subject matter experts)
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## LEGAL BOILERPLATE

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

## EXTRA RESOURCES

- [Sentry Docs contributor guide](https://docs.sentry.io/contributing/)

### CODE REVIEW

**Comment by pasha121** [comment]
Please review 🙏

**Comment by pasha121** [comment]
@azaslavsky please review

**Comment by pasha121** [comment]
@azaslavsky please review

**Comment by pasha121** [comment]
@vaind 
@bruno-garcia 
@chargome
@lfrost 
Please review commit 🙏

**Comment by chargome** [comment]
Hi @pasha121, thanks for opening up a PR! As for the content, the steps you outlined are already present in the google developer documentation in the [link above your changes](https://developers.google.com/identity/sign-in/web/server-side-flow#step_1_create_a_client_id_and_client_secret), so I would rather not add them here.

**Comment by pasha121** [comment]
> Hi @pasha121, thanks for opening up a PR! As for the content, the steps you outlined are already present in the google developer documentation in the [link above your changes](https://developers.google.com/identity/sign-in/web/server-side-flow#step_1_create_a_client_id_and_client_secret), so I would rather not add them here.

But there is no info about redirect URIs for sentry self-hosted. 
I have added info about redirect URIs to avoid of 400 google oauth error.

**Comment by pasha121** [comment]
@chargome

**Pull request closed without merging**
