### PR TITLE
Add PHP code examples to Getting Started docs

### PR DESCRIPTION
**Pull request by benvinegar**
I understand this doesn't use the new "platform" (and that the PHP SDK might not have all the same API methods as the others), but it seems to work.

### CODE REVIEW

**Comment by benvinegar** [comment]
I'm hearing now that this will appear in the application in a broken state, and that nobody seems to understand how that works.

@cameronmcefee help

**Comment by mitsuhiko** [comment]
I will review this.

**Comment by stayallive** [comment]
If this is some kind of shortcut/quick start to the full SDK docs it’s good enough, little sparse (don’t really know how or where its shown). But yes 2.0 will change things but we can update it when thats out, I believe @HazAT already made an start on the 2.0 docs.

**Comment by mitsuhiko** [comment]
For reference the new php docs are here: https://github.com/getsentry/sentry-docs/tree/php/docs

The main note I have now I want to change if we want to merge this is remove the links to the unified SDK options when the PHP dropdown is active or it links to completely wrong content now. Right now all docs in the quickstart link to more pages that are only relevant for the unified SDK.

**Comment by HazAT** [comment]
I think my PR is ready to be merged
https://github.com/getsentry/sentry-docs/pull/609

The new SDK with the unified API is already released (still as `beta1` but it shouldn't matter).

**Comment by HazAT** [comment]
Thanks for the work @benvinegar 
We merged and released the new php sdk / docs so I am closing this now.

**Pull request closed without merging**
