### PR TITLE
feat: Cache api schema for build

### PR DESCRIPTION
**Pull request by HazAT**
Vercel build was error because we make a request for every page we generate, this add a simple cache.

### CODE REVIEW

**Review by lforst — APPROVED** [review]

**Review by cleptric — APPROVED** [review]

**Comment by lforst** [comment]
You may wanna use [react's `cache()` fn](https://react.dev/reference/react/cache) for this. Don't know if it works for static things like that tho.

**Comment by HazAT** [comment]
@lforst  too fancy, merging now

**Comment by mjq-sentry** [comment]
> You may wanna use [react's `cache()` fn](https://react.dev/reference/react/cache) for this. Don't know if it works for static things like that tho.

Actually the exported method that calls this function (`apiCategories`) already uses react's `cache` as of #9069, so tbh I'm really surprised this was still making a request per page 🤔

**Comment by lforst** [comment]
The build logs mention something about something not being able to be cached bc the data is >2MB. Maybe it's not caching it because of that - which would be weird because especially in cases where the data is big, I want it cached. 🤔

**Pull request merged**
