### PR TITLE
fix typo in react documentation

### PR DESCRIPTION
**Pull request by meain**
Local files use relative import

### CODE REVIEW

**Comment by kamilogorek** [comment]
It's very common to configure module resolution so that it can resolve this path just fine, but I agree that docs should show the simplest possible scenario.

**Comment by kamilogorek** [comment]
Although in this case it should rather say `./App` anyway, as `index.js` is usually in the same directory as `App.js`

**Comment by meain** [comment]
Yeah, I think that makes sense. I will switch it to `./App` or should it be `./App.js`?

**Comment by kamilogorek** [comment]
I prefer a form without an extension

**Comment by meain** [comment]
Done!

**Comment by kamilogorek** [comment]
Thanks!

**Pull request merged**
