### PR TITLE
Updated screenshot for Metric Alerts

### PR DESCRIPTION
**Pull request by MimiDumpling**
BEFORE:
image

AFTER:
image

### CODE REVIEW

**Comment by billyvg** [comment]
Do we want this designy mockup, or actual in-app screenshot. Minor nit, the "subscribe" button is current in the "unsubscribe" state.

**Comment by MimiDumpling** [comment]
> Do we want this designy mockup, or actual in-app screenshot. Minor nit, the "subscribe" button is current in the "unsubscribe" state.

In-app screenshot is preferred. Will you send me a better screenshot thru Slack?

**Comment by adhiraj** [comment]
also @MimiDumpling the old alert details screenshot should be the new alert stream screenshot

**Comment by MimiDumpling** [comment]
> also @MimiDumpling the old alert details screenshot should be the new alert stream screenshot

Okay, I'll make the change today. Thanks!

**Comment by MimiDumpling** [comment]
@billyvg I think I'll leave the disigny mockup for now. It's more exciting. It's also okay that the "subscribe" button is in the "unsubscribe" state. It implies that the user has subscribed. 😛

**Pull request merged**
