### PR TITLE
fix: remove bundle map file

### PR DESCRIPTION
**Pull request by cameronmcefee**

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Do we have any assets in that folder we actually want to retain in git?

**Comment by cameronmcefee** [comment]
Currently it's where Reload lives, which isn't a module I can just import with the bundle (as far as I can tell).

**Comment by mitsuhiko** [comment]
I mean it's okay for now. I just found it weird how this is set up. Normally we have a folder that contains all generated things but it seems one file in there is not.

**Comment by cameronmcefee** [comment]
Agreed, it's odd. There's a reason for the split (namely, the cacheable asset urls), but if we can sort out reload (and soon to be Amplitude) we could get them into the main bundle. Alternatively we just don't cache them.

**Pull request merged**
