### PR TITLE
feat(apm): Add markers to be used for inline tracing docs for the product

### PR DESCRIPTION
**Pull request by dashed**
Mark sections of the tracing SDK docs to be used for inline tracing docs on the product.

The corresponding PR in `sentry`: https://github.com/getsentry/sentry/pull/19527

-----

Node.js docs:

Screen Shot 2020-06-24 at 7 37 20 AM

Python docs:

Screen Shot 2020-06-24 at 7 36 04 AM

### CODE REVIEW

**Review by markstory — APPROVED** [review]
🧙‍♂️

**Comment by dashed** [comment]
Blocked by https://github.com/getsentry/sentry-docs/pull/1782

**Review by MimiDumpling — APPROVED** [review]
🌻 Thank you!

**Review by cameronmcefee — APPROVED** [review]
To the extent that I write ruby (limited) this seems fine. I'd probably change `hide` to `hide_from_sidebar` for clarity of what it does

**Pull request merged**
