### PR TITLE
fix: Resolve regex issues in code blocks

### LINKED ISSUE #10468: React instrumentation snippet pastes wrong regex
### Steps to Reproduce

Clicking on the copy button of the intrumentation.js snippet in the react sdk docs and pasting it adds newlines to the pasted regex.

https://docs.sentry.io/platforms/javascript/guides/react/

Update: This issue appears to happen in all snippets that contain a regex.

### Expected Result

```js
// Set `tracePropagationTargets` to control for which URLs trace propagation should be enabled
tracePropagationTargets: [/^\//, /^https:\/\/yourserver\.io\/api/],
```

### Actual Result

```js
// Set `tracePropagationTargets` to control for which URLs trace propagation should be enabled
  tracePropagationTargets: [/
^
\//, /
^
https:\/\/yourserver\.io\/api/],
```

### Additional Info

_No response_

### LINKED ISSUE #10583: UI Bug: ^ and $ symbols not visible
### Steps to Reproduce

1. Navigate to the documentation page
https://docs.sentry.io/platforms/javascript/configuration/filtering/#using-
2. Notice that the regex /Exact Match Message/ is displayed without the ^ and $ anchors
3. Copy the code snippet and paste it into a text editor
4. Verify that the pasted code actually includes the ^ and $ anchors

### Expected Result

The regex in the documentation should visually display the ^ and $ anchors: /^Exact Match Message$/

### Actual Result

The regex is displayed without the visible ^ and $ anchors: /Exact Match Message/

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by chargome**
## DESCRIBE YOUR PR

- Fixes #10583
- Fixes #10468 

## IS YOUR CHANGE URGENT?  

Help us prioritize incoming PRs by letting us know when the change needs to go live.
- [ ] Urgent deadline (GA date, etc.): 
- [ ] Other deadline: 
- [x] None: Not urgent, can wait up to 1 week+

## SLA

- Teamwork makes the dream work, so please add a reviewer to your PRs.
- Please give the docs team up to 1 week to review your PR unless you've added an urgent due date to it.
Thanks in advance for your help!

## PRE-MERGE CHECKLIST

*Make sure you've checked the following before merging your changes:*

- [x] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs (subject matter experts)
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## LEGAL BOILERPLATE

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

## EXTRA RESOURCES

- [Sentry Docs contributor guide](https://docs.sentry.io/contributing/)

### CODE REVIEW

**Review by andreiborza — APPROVED** [review]
nice!

**Comment by a-hariti** [comment]
This breaks header link icons @charliemday 

Screenshot 2024-07-05 at 11 07 13

**Comment by chargome** [comment]
@a-hariti Thanks for catching that, please have another look.

**Review by a-hariti — APPROVED** [review]

**Review by lizokm — APPROVED** [review]
@chargome thanks for these updates. Feel free to merge!

**Pull request merged**
