### PR TITLE
fix: remove incorrect common content

### PR DESCRIPTION
**Pull request by edtam**

### CODE REVIEW

**Comment by HazAT** [comment]
@edtam Whats incorrect here?

**Comment by edtam** [comment]
@HazAT 
This content should belong to the JavaScript version. 
But now it appears on every platform.

[In JavaScript](https://docs.sentry.io/platforms/javascript/configuration/capture/#capturing-errors)
image

[In C#](https://docs.sentry.io/platforms/dotnet/configuration/capture/#capturing-errors)
image

[In Flutter](https://docs.sentry.io/platforms/flutter/configuration/capture/#capturing-errors)
image

**Review by rhcarvalho — APPROVED** [review]
Thanks @edtam!

This file is used as a "base template", shouldn't have references to JavaScript.


Going to merge this, @getsentry/docs FYI in case you want to review the file as a whole in a follow up.

**Review by PeloWriter — COMMENTED** [review]
Thank you.

**Pull request merged**
