### PR TITLE
Update index.mdx

### PR DESCRIPTION
**Pull request by RChutchev**
## Pre-merge checklist

*If you work at Sentry, you're able to merge your own PR without review, but please don't unless there's a good reason.*

- [ ] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## Description of changes

Correct name is isRequiredLabel, not a isRequiredText.

     /**
     * Label shown when an input field is required
     */
    isRequiredLabel: string;

## Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

## Extra resources

- [Sentry Docs contributor guide](https://docs.sentry.io/contributing/)

### CODE REVIEW

**Comment by billyvg** [comment]
@vivianyentran `isRequiredText` is correct: https://github.com/getsentry/sentry-javascript/blob/7db32686ff42fad17c0a16329c2567ea85289de4/packages/feedback/src/modal/components/Form.tsx#L179

**Comment by RChutchev** [comment]
Hi @billyvg, @vivianyentran

Yep, you right, but something wrong... 
b/c when I'm trying to use feedback.attachTo from "@sentry/browser" field named as isRequiredLabel not as isRequiredText.


node_modules/@sentry-internal/feedback/types/types/index.d.ts
```
export interface FeedbackTextConfiguration {
    /**
     * The label for the Feedback widget button that opens the dialog
     */
    buttonLabel: string;
    /**
     * The label for the Feedback form cancel button that closes dialog
     */
    cancelButtonLabel: string;
    /**
     * The label for the Feedback form submit button that sends feedback
     */
    submitButtonLabel: string;
    /**
     * The title of the Feedback form
     */
    formTitle: string;
    /**
     * Label for the email input
     */
    emailLabel: string;
    /**
     * Placeholder text for Feedback email input
     */
    emailPlaceholder: string;
    /**
     * Label for the message input
     */
    messageLabel: string;
    /**
     * Placeholder text for Feedback message input
     */
    messagePlaceholder: string;
    /**
     * Label for the name input
     */
    nameLabel: string;
    /**
     * Placeholder text for Feedback name input
     */
    namePlaceholder: string;
    /**
     * Message after feedback was sent successfully
     */
    successMessageText: string;
    /**
     * Label shown when an input field is required
     */
    isRequiredLabel: string;
}
```


I mean, something like this... for example when I trying to use a translation for isRequiredText, 
```
const feedback = Sentry.feedbackIntegration({
                    autoInject: false,
                    colorScheme: "light",
                    isNameRequired: true,
                    isEmailRequired: true,
                    showBranding: false,
            });
            feedback.attachTo(document.querySelector("#feedback"), {
                submitButtonLabel: this.$t("Sentry_Send_Bug_Report"),
                cancelButtonLabel: this.$t("cancel"),
                formTitle: this.$t("Sentry_Report_a_Bug"),
                nameLabel: this.$t("Your Name"),
                namePlaceholder: this.$t("Your Name"),
                emailLabel: this.$t("email"),
                emailPlaceholder: "your.email@example.org",
                messageLabel: this.$t("Sentry_Description"),
                messagePlaceholder: this.$t("Sentry_Message_Placeholder"),
                successMessageText: this.$t("Sentry_SuccessMessageText"),
                isRequiredLabel: this.$t("Sentry_isRequiredText")
            });
```

**Comment by RChutchev** [comment]
IDK (docs error or bug in package) but that's translation to Russian (for example)  

This way is described in docs https://docs.sentry.io/platforms/javascript/guides/vue/user-feedback/configuration/#bring-your-own-widget (according to docs "You can additionally supply the same customization options that the constructor accepts")

first one isRequiredLabel
Screenshot 2024-05-04 at 6 53 22 AM
Screenshot 2024-05-04 at 6 47 33 AM

This one is isRequiredText
Screenshot 2024-05-04 at 6 52 48 AM
Screenshot 2024-05-04 at 6 52 11 AM


That's feedbackIntegration package with previous  import * as Sentry from "@sentry/browser";

**Comment by billyvg** [comment]
Thanks @RChutchev we're currently investigating and will be updating this configuration key as well as adding some new ones.

**Pull request closed without merging**
