### PR TITLE
feat: Add tool to look for core doc issues

### PR DESCRIPTION
**Pull request by dcramer**
Currently only identifies missing wizard content.

### CODE REVIEW

**Comment by dcramer** [comment]
```
Missing wizard content for go -> martini
Missing wizard content for go -> fasthttp
Missing wizard content for go -> echo
Missing wizard content for go -> iris
Missing wizard content for go -> negroni
Missing wizard content for go -> http
Missing wizard content for go -> gin
Missing wizard content for native -> crashpad
Missing wizard content for native -> ue4
Missing wizard content for native -> breakpad
Missing wizard content for native -> minidumps
Missing wizard content for python -> gcp-functions
Missing wizard content for python -> pyspark
Missing wizard content for python -> aws-lambda
Missing wizard content for python -> airflow
Missing wizard content for python -> azure-functions
Missing wizard content for python -> beam
Missing wizard content for python -> logging
Missing wizard content for perl
Missing wizard content for rust -> actix-web
Missing wizard content for java -> google-app-engine
Missing wizard content for java -> spring
Missing wizard content for dotnet
Missing wizard content for dotnet -> aspnetcore
Missing wizard content for dotnet -> log4net
Missing wizard content for dotnet -> extensions-logging
Missing wizard content for dotnet -> entityframework
Missing wizard content for dotnet -> wpf
Missing wizard content for dotnet -> winforms
Missing wizard content for dotnet -> serilog
Missing wizard content for dotnet -> nlog
Missing wizard content for android
Missing wizard content for javascript -> cordova
Missing wizard content for javascript -> gatsby
Missing wizard content for javascript -> electron
Missing wizard content for node -> gcp-functions
Missing wizard content for node -> aws-lambda
Missing wizard content for node -> azure-functions
Missing wizard content for ruby -> puma
```

**Comment by dcramer** [comment]
follow-up would be to also look for ones which exist in wizard and dont exist in guides. those could possibly be valid (tho seems unlikely).

**Comment by dcramer** [comment]
Once we fix these we can make this fail the build, but for now I'll leave it up to folks to use this to identify work that needs done.

**Comment by benvinegar** [comment]
Love this.

**Comment by PeloWriter** [comment]
@HazAT - I'll create a subtask in Asana as part of the migration to new docs for each of the items on this list, adding the need for wizard content.

**Pull request merged**
