### PR TITLE
chore(github): Document new github alert rule action in docs

### PR DESCRIPTION
**Pull request by schew2381**
Basically copied format from [Jira docs](https://docs.sentry.io/product/integrations/issue-tracking/jira/#issue-management) and [Azure docs](https://docs.sentry.io/product/integrations/source-code-mgmt/azure-devops/#issue-management)

See changes [here](https://sentry-docs-git-seiji-choredocument-new-github-action.sentry.dev/product/integrations/source-code-mgmt/github/#issue-management)

### CODE REVIEW

**Comment by Dhrumil-Sentry** [comment]
@schew2381 this is not rendering correctly
image

**Comment by schew2381** [comment]
> @schew2381 this is not rendering correctly image

whoops, fixed the image link

**Comment by schew2381** [comment]
> @schew2381 this is not rendering correctly image

is correct now

**Comment by schew2381** [comment]
> @schew2381 this is not rendering correctly image

**Review by Dhrumil-Sentry — APPROVED** [review]

**Comment by schew2381** [comment]
> @schew2381 this is not rendering correctly image

It's correct now
Screenshot 2023-11-03 at 1 52 00 PM

**Pull request merged**
