### PR TITLE
feat(auth permission): Add information about how to set scopes

### PR DESCRIPTION
**Pull request by ceorourke**
Add information to the [Permissions & Scopes](https://docs.sentry.io/api/permissions/) page about how to set scopes on auth tokens and integration tokens. 

Screen Shot 2020-10-26 at 10 44 58 AM

### CODE REVIEW

**Comment by ceorourke** [comment]
I thought about adding a screenshot of the scopes of the integration token but you see the exact same info on the linked page.

**Comment by manuzope** [comment]
I like the wording. But can we put integration tokens above the auth tokens? Trying to encourage people to use integration tokens over auth tokens.

**Comment by MimiDumpling** [comment]
Will take a look today, @ceorourke

**Review by MimiDumpling — APPROVED** [review]
Aside from Manu's suggestion, this looks good to me. 😸 Thanks for updating Docs!

**Review by manuzope — APPROVED** [review]

**Pull request merged**
